import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    // Vite's default host resolves to the IPv6 loopback on this machine, so a browser that reaches
    // localhost over IPv4 got connection refused. Pin the IPv4 loopback, which is what browsers here try.
    host: "127.0.0.1",
    watch: {
      // public/ holds the generated catalog: 54,982 files in public/o alone, plus public/p. Watching
      // that many files pins the dev server's event loop on Windows and every module request crawls.
      // They are generated by backend sync and never hand-edited, so nothing here needs hot reload.
      // Ignoring them only drops the watcher, they are still served as static files exactly as before.
      ignored: ["**/public/o/**", "**/public/p/**", "**/backend/**", "**/dist/**"],
    },
    // Dev serves every module as its own request and transforms it on first ask. Cold that is around
    // 700ms each and the first page view wears all of it. Warm the heavy entries while the server boots,
    // so the cost lands during startup instead. A warm module answers in about 17ms.
    warmup: {
      clientFiles: [
        "./src/main.tsx",
        "./src/App.tsx",
        "./src/state/AppProvider.tsx",
        "./src/components/web/WebHome.tsx",
        "./src/components/web/WebListing.tsx",
        "./src/components/booking/Sheets.tsx",
        "./src/components/operator/OperatorView.tsx",
        "./src/components/operator/OpLogin.tsx",
      ],
    },
  },
});
