import { defineConfig, loadEnv, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { withApiOrigin, withApiPreconnect } from "./src/lib/csp";

/**
 * The CSP in index.html named the production API host and nothing else, so a build pointed anywhere else could
 * not talk to its own API: Chromium refused every fetch and the app took that for "no API today". This puts the
 * origin the build was pointed at into connect-src, in dev and in a build alike, and opens the connection to it
 * early with a preconnect, so the first call the page makes does not pay for a handshake. See src/lib/csp.ts.
 *
 * `loadEnv` rather than `process.env` because it reads the .env files and the inline VITE_ variables the same
 * way the app's own `import.meta.env.VITE_API_URL` is read, so the policy cannot name a different host than the
 * one the bundle calls.
 */
function cspApiOrigin(mode: string): Plugin {
  const apiUrl = loadEnv(mode, ".", "VITE_").VITE_API_URL;
  return {
    name: "outset-csp-api-origin",
    transformIndexHtml: {
      order: "pre",
      handler: (html) => withApiPreconnect(withApiOrigin(html, apiUrl), apiUrl),
    },
  };
}

/**
 * The clean URLs production has. render.yaml rewrites /otto, /about, /terms and /privacy to their .html files
 * ahead of the SPA catch-all; without the same rule here, /otto on the dev server fell through to the app and
 * showed the guest home, so every local check of the Otto page had to be typed as /otto.html.
 */
const CLEAN_URLS: Record<string, string> = { "/otto": "/otto.html", "/about": "/about.html", "/terms": "/terms.html", "/privacy": "/privacy.html" };
function cleanUrls(): Plugin {
  const rewrite = (server: { middlewares: { use: (fn: (req: { url?: string }, res: unknown, next: () => void) => void) => void } }) => {
    server.middlewares.use((req, _res, next) => {
      const path = (req.url || "").split("?")[0].replace(/\/$/, "") || "/";
      const target = CLEAN_URLS[path];
      if (target) req.url = target + ((req.url || "").includes("?") ? "?" + (req.url || "").split("?")[1] : "");
      next();
    });
  };
  return { name: "outset-clean-urls", configureServer: rewrite, configurePreviewServer: rewrite };
}

export default defineConfig(({ mode }) => ({
  plugins: [react(), cspApiOrigin(mode), cleanUrls()],
  server: {
    // Vite's default host resolves to the IPv6 loopback on this machine, so a browser that reaches
    // localhost over IPv4 got connection refused. Pin the IPv4 loopback, which is what browsers here try.
    host: "127.0.0.1",
    watch: {
      // public/ holds the generated catalog: 54,982 files in public/o alone, plus public/p. Watching
      // that many files pins the dev server's event loop on Windows and every module request crawls.
      // They are generated by backend sync and never hand-edited, so nothing here needs hot reload.
      // Ignoring them only drops the watcher, they are still served as static files exactly as before.
      ignored: ["**/public/o/**", "**/public/p/**", "**/backend/**", "**/dist/**"],
    },
    // Dev serves every module as its own request and transforms it on first ask. Cold that is around
    // 700ms each and the first page view wears all of it. Warm the heavy entries while the server boots,
    // so the cost lands during startup instead. A warm module answers in about 17ms.
    warmup: {
      clientFiles: [
        "./src/main.tsx",
        "./src/App.tsx",
        "./src/state/AppProvider.tsx",
        "./src/components/web/WebHome.tsx",
        "./src/components/web/WebListing.tsx",
        "./src/components/booking/Sheets.tsx",
        "./src/components/operator/OperatorView.tsx",
        "./src/components/operator/OpLogin.tsx",
      ],
    },
  },
}));
