import "../src/env.ts";
import { writeFileSync } from "node:fs";
import { db } from "../src/db/client.ts";
import { composeOutreach } from "../src/outreach/drafts.ts";
import { outreachAddress } from "../src/outreach/address.ts";
const op = db.prepare(`SELECT * FROM operators o WHERE domain = 'sunsetwatersportskeywest.com'`).get() as any;
const to = outreachAddress(op) || op.email;
const { subject, body } = composeOutreach(op, to);
const out = "To: " + to + "\nFrom: " + (process.env.MAIL_FROM || "Harshil <hello@onoutset.com>") + "\nSubject: " + subject + "\n\n" + body + "\n";
writeFileSync("data/sample-claim-email.txt", out);
console.log(out);
process.exit(0);
