import { mkdirSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { db } from "../db/client.ts";
import { writeLandingPages } from "./pages.ts";

const here = dirname(fileURLToPath(import.meta.url));
const appDataDir = join(here, "../../../src/data");

/** Public contact facts for one operator. Every field is null when the site did not publish it. */
export type OperatorContact = {
  domain: string;
  website: string | null;
  phone: string | null;
  email: string | null;
  street: string | null;
  city: string | null;
  region: string | null;
  postal: string | null;
  hours: string[];
  bookingVendor: string | null;
  fetchedAt: string | null;
};

type Row = {
  domain: string;
  website: string | null;
  phone: string | null;
  email: string | null;
  street: string | null;
  city: string | null;
  region: string | null;
  postal: string | null;
  hours: string | null;
  hours_text: string | null;
  calendar_vendor: string | null;
  fetched_at: string | null;
};

export function contactFor(domain: string): OperatorContact | null {
  const row = db
    .prepare(
      `SELECT o.domain, o.website, o.phone, o.email, o.street, o.city, o.region, o.postal, o.hours, o.calendar_vendor,
              (SELECT MAX(fetched_at) FROM sources s WHERE s.operator_id = o.id AND s.http_status = 200) AS fetched_at
       FROM operators o WHERE o.domain = ?`,
    )
    .get(domain) as Row | undefined;
  return row ? toContact(row) : null;
}

export function allContacts(): OperatorContact[] {
  const rows = db
    .prepare(
      `SELECT o.domain, o.website, o.phone, o.email, o.street, o.city, o.region, o.postal, o.hours, o.calendar_vendor,
              (SELECT fact_value FROM facts f WHERE f.operator_id = o.id AND f.fact_key = 'hours_text' LIMIT 1) AS hours_text,
              (SELECT MAX(fetched_at) FROM sources s WHERE s.operator_id = o.id AND s.http_status = 200) AS fetched_at
       FROM operators o WHERE o.origin != 'demo' ORDER BY o.domain`,
    )
    .all() as Row[];
  return rows.map(toContact);
}

function toContact(r: Row): OperatorContact {
  return {
    domain: r.domain,
    website: r.website,
    phone: silent(r.phone),
    email: r.email,
    street: r.street,
    city: r.city,
    region: r.region,
    postal: r.postal,
    hours: (r.hours ? r.hours.split(" | ").map((h) => h.trim()).filter(Boolean) : r.hours_text ? [r.hours_text.replace(/^hours:?\s*/i, "").trim()] : []).filter((h) => !SILENT.test(h)),
    bookingVendor: r.calendar_vendor,
    fetchedAt: r.fetched_at,
  };
}

/**
 * Write src/data/contacts.ts for the hand-verified seed operators only. Everything else ships in public/catalog.json,
 * which the app fetches at startup, so the bundled file stays small.
 */
export function syncContactsToApp(): { path: string; count: number } {
  const seedDomains = new Set(
    (db.prepare("SELECT domain FROM operators WHERE origin IN ('seed', 'public_site')").all() as { domain: string }[]).map((r) => r.domain),
  );
  const contacts = allContacts().filter((c) => seedDomains.has(c.domain));
  const body = contacts
    .map((c) => "  " + JSON.stringify(c.domain) + ": " + JSON.stringify(c) + ",")
    .join("\n");
  const src = `import type { OperatorContact } from "./types";

/**
 * GENERATED by \`npm run backend:sync\`. Do not edit by hand.
 * Public contact facts per operator domain, copied from each company's own site by the backend scraper.
 * A null field means the site did not publish it. Do not fill gaps by hand.
 */
export const CONTACTS: Record<string, OperatorContact> = {
${body}
};
`;
  const path = join(appDataDir, "contacts.ts");
  writeFileSync(path, src);
  return { path, count: contacts.length };
}

/* ---------- Full catalog export for the guest app ---------- */

type CatalogRow = {
  id: string;
  domain: string;
  name: string;
  website: string | null;
  city: string | null;
  region: string | null;
  metro_id: string | null;
  family: string | null;
  icon_key: string;
  rating: number | null;
  review_count: number | null;
  origin: string;
  lat: number | null;
  lon: number | null;
};

/** Marketplaces and directories are not operators. They never belong in the catalog. */
/** Names the discovery net caught that are not something a guest books: car rentals, retail, festivals, museums, clubs, public piers. */
export const NOT_EXPERIENCE = /\bcar rentals?\b|\brent-?a-?car\b|\b(thrifty|hertz|avis|enterprise|budget) \b|u-haul|\bauto rentals?\b|\bsports? shop\b|\bski sports\b|\bsporting goods\b|\bfestival\b|\bfair\b(?! ?winds)|\bmuseum\b|\browing club\b|\byacht club\b|\bmunicipal pier\b|\bcommunity boathouse\b|\bboat ramp\b|\bpublic launch\b|\bstate park\b|\bcounty park\b/i;
export const MARKETPLACES = /(^|\.)(sailo|getmyboat|boatsetter|viator|tripadvisor|airbnb|expedia|groupon|yelp|peek|fareharbor|getyourguide|klook|eventbrite|meetup|facebook|instagram|booking|hotels|vrbo|kayak|tours4fun|musement|headout|goldstar|boatbound|clickandboat|samboat|fishingbooker|fishanywhere|guidesly)\.(com|net|co|io|ca)$/i;

const DEFAULT_GAP = "Prices, hours and eligibility are not copied here yet. We will ask when you request.";

/** A chain's other venues, for nearest-location distance. Empty for the usual single-site operator. */
function extraLocations(operatorId: string): { city: string; region?: string; lat: number; lon: number; street?: string }[] | undefined {
  const rows = db
    .prepare("SELECT city, region, street, lat, lon FROM locations WHERE operator_id = ? ORDER BY city LIMIT 60")
    .all(operatorId) as { city: string | null; region: string | null; street: string | null; lat: number; lon: number }[];
  if (!rows.length) return undefined;
  return rows.map((l) => ({ city: l.city || "Nearby", region: l.region || undefined, lat: Math.round(l.lat * 1e4) / 1e4, lon: Math.round(l.lon * 1e4) / 1e4, street: l.street || undefined }));
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
}

/** One operator in the shape the guest app's Unclaimed type expects. Facts only, nothing invented. */
function toCatalogItem(r: CatalogRow): Record<string, unknown> {
  const offerings = db
    .prepare("SELECT name, detail, duration, price_cents, price_unit FROM offerings WHERE operator_id = ? ORDER BY price_cents IS NULL, price_cents")
    .all(r.id) as { name: string; detail: string | null; duration: string | null; price_cents: number | null; price_unit: string | null }[];
  const facts = db.prepare("SELECT fact_key, fact_value, source_url FROM facts WHERE operator_id = ?").all(r.id) as { fact_key: string; fact_value: string; source_url: string | null }[];
  const pick = (k: string) => facts.filter((f) => f.fact_key === k).map((f) => (/^(photo|video|yt_video|social:)/.test(k) ? f.fact_value : decodeEntities(f.fact_value)));
  // Booking-widget item photos are the operator's own curated product shots. They beat whatever the crawl scored highest.
  const widgetPhotos = uniq(facts.filter((f) => f.fact_key === "photo" && /fareharbor|xola|filestack/i.test((f.source_url || "") + " " + f.fact_value)).map((f) => f.fact_value));
  const area = r.city ? (r.region && !r.city.includes(r.region) ? r.city + ", " + r.region : r.city) : r.region || "";
  return {
    id: "o-" + slug(r.domain),
    title: decodeEntities(r.name),
    cat: r.family || "water",
    art: artFromName(r.name, r.icon_key),
    area,
    metroId: r.metro_id || "",
    src: r.domain,
    rating: r.rating ?? undefined,
    reviews: r.review_count ?? undefined,
    specs: [...pick("spec"), ...pick("requirement"), ...pick("group")].slice(0, 10),
    options: offerings.map((o) => ({
      name: o.name,
      detail: silent(o.duration) || silent(o.detail) || "",
      price: o.price_cents == null ? null : o.price_cents / 100,
      per: o.price_unit && o.price_unit.startsWith("/") ? o.price_unit : undefined,
    })),
    services: (() => {
      const descs = new Map<string, string>();
      for (const raw of pick("service_desc")) {
        try {
          const d = JSON.parse(raw) as { name: string; desc: string };
          descs.set(d.name.toLowerCase(), d.desc);
        } catch {
          /* ignore */
        }
      }
      const photos = new Map<string, string>();
      for (const raw of pick("service_photo")) {
        try {
          const d = JSON.parse(raw) as { name: string; url: string };
          photos.set(d.name.toLowerCase(), d.url);
        } catch {
          /* ignore */
        }
      }
      const groups = new Map<string, { name: string; desc: string | null; photo?: string; variants: { label: string; price: number | null; per?: string; optionIdx: number }[] }>();
      offerings.forEach((o, idx) => {
        const key = o.name.toLowerCase();
        if (NOT_A_SERVICE.test(o.name)) return;
        const g = groups.get(key) || { name: o.name, desc: descs.get(key) || null, photo: fullSize(photos.get(key) || "") || undefined, variants: [] };
        g.variants.push({
          label: silent(o.duration) || silent(o.detail) || "Standard",
          price: o.price_cents == null ? null : o.price_cents / 100,
          per: o.price_unit && o.price_unit.startsWith("/") ? o.price_unit : undefined,
          optionIdx: idx,
        });
        groups.set(key, g);
      });
      return [...groups.values()].filter((g) => !/gift ?cards?|gift certificate|deposit|membership|season pass/i.test(g.name)).slice(0, 14);
    })(),
    includes: uniq(pick("includes").map(cleanLine)).filter(isTidyLine).filter((l) => !/gift ?card|gift certificate|will be provided upon|directions will|upon purchas/i.test(l)).slice(0, 10),
    addons: pick("addon")
      .map((a) => {
        const m = a.match(/^(.*?)\s*\$(\d+(?:\.\d+)?)$/);
        return m ? { name: m[1].trim().replace(/\s+(for|at|only|just|from|is)$/i, ""), detail: "", price: Number(m[2]) } : null;
      })
      .filter((a): a is { name: string; detail: string; price: number } => !!a)
      // "An additional $35" is a fee sentence, not something a guest adds to a cart.
      .filter((a) => a.name.length >= 3 && !/^(an?|the|plus|extra|additional|only|just|from|starting|starts|add|adds|is|are|and|or|for)\b/i.test(a.name) && !/\b(fee|surcharge|deposit|tax|gratuity|tip|per person|per hour)\b/i.test(a.name))
      .slice(0, 6),
    // The honest gap line. Once the widget or crawl gave real rules and policies, say those instead of "not copied yet".
    gap: pick("published_gap")[0] || pick("cancellation")[0] || (pick("policy").length || pick("requirement").length ? [...pick("policy")].slice(0, 3).join(" ") || "Ask the operator about cancellations." : DEFAULT_GAP),
    blurb: pick("description")[0] || pick("site_desc")[0] || pick("one_line")[0] || undefined,
    cover: fullSize(widgetPhotos[0] || pick("cover")[0] || pick("photo")[0] || ""),
    photos: uniq([...widgetPhotos, ...pick("cover"), ...pick("photo")].map((u) => fullSize(u) || "")).slice(0, 10),
    ytVideos: pick("yt_video")
      .map((raw) => {
        try {
          const v = JSON.parse(raw) as { id: string; title: string; views: number };
          return { id: v.id, title: v.title, views: v.views };
        } catch {
          return null;
        }
      })
      .filter((v): v is { id: string; title: string; views: number } => !!v)
      .slice(0, 3),
    tiktok: pick("tiktok_profile")[0] || undefined,
    instagram: pick("social:instagram")[0] || undefined,
    video: pick("video")[0] || undefined,
    videoEmbed: pick("video_embed")[0] || undefined,
    lat: r.lat ?? undefined,
    lon: r.lon ?? undefined,
    locations: extraLocations(r.id),
    tags: [...new Set([...pick("google_category"), ...pick("service"), ...offerings.map((o) => o.name)])].slice(0, 12),
    extraNote: [...pick("extra").slice(0, 1), ...pick("policy"), ...pick("checkin"), ...pick("meeting_point"), ...pick("season")].filter((l) => !SILENT.test(l)).join(" · ").slice(0, 700) || undefined,
    // Viator-shaped sections. Each only appears when the site said it.
    highlights: uniq(pick("spec").map(cleanLine)).filter(isTidyLine).slice(0, 8),
    requirements: collapseRules(uniq(pick("requirement").map(cleanLine)).filter(isTidyLine)).slice(0, 10),
    groupInfo: uniq(pick("group").map(cleanLine)).filter(isTidyLine).slice(0, 5),
    bring: uniq(pick("bring").map(cleanLine)).filter(isTidyLine).slice(0, 8),
    season: silent(cleanLine(pick("season")[0] || "")) || undefined,
    meetingPoint: cleanLine(pick("meeting_point")[0] || "") || undefined,
    checkin: cleanPara(pick("checkin")[0] || "") || undefined,
    cancellation: dropSilent(cleanPara(pick("cancellation")[0] || "")) || dropSilent(cleanPara(pick("policy").filter((l) => /cancel|refund/i.test(l)).join(" "))) || undefined,
    policies: uniq(pick("policy").map(cleanLine)).filter(isTidyLine).filter((l) => !/gift ?card|gift certificate/i.test(l)).slice(0, 8),
    waiverUrl: pick("waiver_url").find((u) => /^https?:\/\/\S+$/.test(u) && !/\/w\/?$/.test(u)) || undefined,
    hoursText: uniq(pick("hours_text").map((h) => cleanLine(h.replace(/^hours(?: & admission)?\s*/i, "")))).slice(0, 3),
    faq: uniqBy(pick("faq").flatMap(parseFaqs), (f) => f.q.toLowerCase()).slice(0, 8),
    dur: durationOf(offerings.map((o) => o.duration || o.detail || "")) || undefined,
    fc: freeCancel(cleanPara(pick("cancellation")[0] || "") || pick("policy").filter((l) => /cancel|refund/i.test(l)).join(" ")) || undefined,
  };
}

/** "2 hours", "90 min", "1 to 4 hours": the first duration the menu states. */
function durationOf(texts: string[]): string | null {
  for (const t of texts) {
    const m = t.match(/\b(\d+(?:\.\d+)?)\s*(?:-|to)?\s*(\d+)?\s*(hours?|hrs?|minutes?|mins?|days?)\b/i);
    if (!m) continue;
    const n = Number(m[2] || m[1]);
    if (/notice|advance|prior|before|cancel|refund/i.test(t)) continue;
    const isMin = /min/i.test(m[3]);
    const isDay = /day/i.test(m[3]);
    // A booking is minutes to a day or two. Anything longer is a policy window that leaked into the menu text.
    if ((isMin && n > 600) || (!isMin && !isDay && n > 14) || (isDay && n > 7)) continue;
    const unit = isMin ? "min" : isDay ? (n === 1 ? "day" : "days") : n === 1 ? "hour" : "hours";
    return (m[2] ? m[1] + " to " + m[2] : m[1]) + " " + unit;
  }
  return null;
}

/** "Free cancellation up to 48 hours before", only when the operator's own words promise a full refund. */
function freeCancel(text: string): string | null {
  if (!text || !/full refund|free cancellation|100% refund|fully refundable/i.test(text)) return null;
  if (/non-?refundable|no refunds?\b/i.test(text) && !/full refund/i.test(text)) return null;
  const m = text.match(/(\d+)\s*(hours?|hrs?|days?)/i);
  if (!m) return "Free cancellation";
  const n = Number(m[1]);
  const unit = /day/i.test(m[2]) ? (n === 1 ? "day" : "days") : n === 1 ? "hour" : "hours";
  return "Free cancellation up to " + n + " " + unit + " before";
}

/** "Hawaiian Parasail" is parasailing whatever OpenStreetMap tagged it. The name wins when it names the activity outright. */
const ART_BY_NAME: [RegExp, string][] = [
  [/\bparasail/i, "parasail"],
  [/\bjet ?ski|waverunner|sea-?doo/i, "jetski"],
  [/\bskydiv|\btandem jump|\bparachut/i, "skydive"],
  [/\baxe|\bhatchet/i, "axe"],
  [/\bescape (room|game)|\bescape\b/i, "escape"],
  [/\bkart|\bkarting/i, "kart"],
  [/\bpaintball|\bairsoft|\blaser tag/i, "paintball"],
  [/\bhelicopter|\bheli\b|\bhelitour/i, "heli"],
  [/\bballoon/i, "balloon"],
  [/\bkayak|\bpaddle ?board|\bcanoe|\bsup\b|\bpaddl/i, "kayak"],
  [/\bpontoon/i, "pontoon"],
  [/\bhorse|\bequestrian|\btrail ride|\bstable/i, "horse"],
  [/\bfishing|\bcharter fish|\bsportfish|\bangl/i, "fishing"],
  [/\bsunset (cruise|sail)|\bcruise|\bsailing|\bcatamaran|\byacht/i, "cruise"],
];
function artFromName(name: string, fallback: string): string {
  for (const [re, art] of ART_BY_NAME) if (re.test(name)) return art;
  return fallback;
}

/** One clean statement: not a question, not a mashed paragraph, not a scraped aside. */
/** "Must be 21 with ID" and "All participants must be age 21 or older with a valid ID" say one thing. Keep the shortest per topic. */
function collapseRules(lines: string[]): string[] {
  const byKey = new Map<string, string>();
  const order: string[] = [];
  for (const l of lines) {
    const nums = (l.match(/\d+/g) || []).join(",");
    const topic = /\b(age|years?|old|older|minor|child|kid|adult|\d+\s*\+)\b/i.test(l) ? "age" : /\b(weight|lbs?|pounds?|kg)\b/i.test(l) ? "weight" : /\b(height|tall|inches|cm)\b/i.test(l) ? "height" : /\b(licen[cs]e|permit|boater)\b/i.test(l) ? "license" : "";
    const key = topic && nums ? topic + ":" + nums : l.toLowerCase();
    const cur = byKey.get(key);
    if (!cur) {
      byKey.set(key, l);
      order.push(key);
    } else if (l.length < cur.length) byKey.set(key, l);
  }
  return order.map((k) => byKey.get(k)!);
}

/** Wix lazy-load placeholders are 34px blurred stubs. Ask for the full image instead; tiny variants from other hosts are dropped. */
function fullSize(u: string): string | undefined {
  if (!u) return undefined;
  const wix = u.match(/^(https?:\/\/static\.wixstatic\.com\/media\/[^/]+?)(?:\/v1\/|$)/);
  if (wix) return wix[1] + "/v1/fill/w_1600,h_1000,al_c,q_85/" + wix[1].split("/media/")[1].replace(/%7E/gi, "~");
  if (/[?&/](w|width)[=_]\d{1,2}\b|[?&/](h|height)[=_]\d{1,2}\b|blur_\d|\/w_1?\d{2},h_\d{2}\b/.test(u)) return undefined;
  return u;
}

const SILENT = /\b(not|no|none|nothing)\b[^.]{0,50}\b(stated|specified|listed|mentioned|provided|published|given|indicated)\b|\bnot (state|specify|mention|list)\b|\bunspecified\b|\bn\/a\b|\bno information\b/i;
/** A value that only says "not stated" is no value. */
function silent(v: string | null | undefined): string | null {
  return v && !SILENT.test(v) ? v : null;
}
/** Remove sentences that only say a policy is absent. */
function dropSilent(t: string): string {
  return t.split(/(?<=[.!?])\s+/).filter((x) => !SILENT.test(x)).join(" ").trim();
}

function isTidyLine(l: string): boolean {
  if (l.length < 6 || l.length > 150) return false;
  // "Deposit policy not stated" tells a guest nothing; the extractor writes these when a site is silent.
  if (SILENT.test(l)) return false;
  if (/\?\s*$/.test(l) || /\?\s+[A-Z]/.test(l)) return false;
  if (/^(and|but|or|so|also|please note|note:|p\.s\.)\b/i.test(l)) return false;
  if (/\b(duration|meeting location|rates?)\b.*\$\d/i.test(l)) return false;
  if (/not limited to|click|subscribe|newsletter|follow us/i.test(l)) return false;
  return true;
}

/** Things a site sells that a guest does not book a time for. */
const NOT_A_SERVICE = /\b(gift ?cards?|gift certificates?|e-?gift|merch(andise)?|t-?shirts?|hats?|apparel|donation|membership|season pass|parking)\b/i;

function uniq(list: string[]): string[] {
  const seen = new Set<string>();
  return list.filter((x) => x && !seen.has(x.toLowerCase()) && (seen.add(x.toLowerCase()), true));
}

const NAMED: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ", rsquo: "\u2019", lsquo: "\u2018", ldquo: "\u201c", rdquo: "\u201d", ndash: "\u2013", mdash: "\u2014", hellip: "\u2026", copy: "\u00a9", reg: "\u00ae", trade: "\u2122", deg: "\u00b0", eacute: "\u00e9" };
/** Sites leave HTML entities in meta descriptions and menus. Guests should never see "&amp;". Runs twice for double-encoded text. */
export function decodeEntities(raw: string): string {
  const once = (t: string) =>
    t.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, code: string) => {
      if (code[0] === "#") {
        const n = code[1].toLowerCase() === "x" ? parseInt(code.slice(2), 16) : parseInt(code.slice(1), 10);
        return Number.isFinite(n) && n > 0 ? String.fromCodePoint(n) : m;
      }
      return NAMED[code.toLowerCase()] ?? m;
    });
  return once(once(raw));
}

/** Markdown, image tags and widget leftovers out; one clean sentence in. */
function cleanLine(raw: string): string {
  return raw
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[#*_>`]+/g, " ")
    .replace(/https?:\/\/\S+/g, "")
    .replace(/^\s*(?:\(?\d{1,2}[.)]|[-–•·]|[a-z][.)]|[AQ]\s*[-–:])\s+/i, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 240);
}

function cleanPara(raw: string): string {
  const flat = raw
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[#*_>`]+/g, " ")
    .replace(/https?:\/\/\S+/g, "")
    .replace(/\s+/g, " ")
    .trim();
  // Sites repeat the same sentence in two places. Keep each once, and never cut mid-sentence.
  const seen = new Set<string>();
  const out: string[] = [];
  let len = 0;
  for (const sentence of flat.split(/(?<=[.!?])\s+(?=[A-Z0-9"(])/)) {
    const key = sentence.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
    if (!key || seen.has(key)) continue;
    if (len + sentence.length > 700) break;
    seen.add(key);
    out.push(sentence);
    len += sentence.length + 1;
  }
  if (out.length > 1 && !/[.!?)"]$/.test(out[out.length - 1])) out.pop();
  return out.join(" ");
}

/** FAQ facts come as "Question? >Answer", "Q – Question? A – Answer", or several of those packed together. */
function parseFaqs(raw: string): { q: string; a: string }[] {
  const t = cleanPara(raw).replace(/\bA\s*[-–:]\s*/g, " ").trim();
  const chunks = t.split(/\bQ\s*[-–:.]\s*/).map((c) => c.trim()).filter(Boolean);
  const out: { q: string; a: string }[] = [];
  for (const c of chunks) {
    const i = c.indexOf("?");
    if (i < 8 || i > 160) continue;
    const before = c.slice(0, i + 1);
    const cut = Math.max(before.lastIndexOf(". "), before.lastIndexOf("! "));
    const q = before.slice(cut === -1 ? 0 : cut + 2).replace(/^[\s\-–—•·:]+/, "").trim();
    // The answer ends where the next question begins.
    let a = c.slice(i + 1).replace(/^\s*>\s*/, "").trim();
    const next = a.search(/[.!]\s+[A-Z][^.!?]{8,120}\?/);
    if (next > 20) a = a.slice(0, next + 1);
    if (q.length < 8 || a.length < 12) continue;
    out.push({ q, a: a.slice(0, 500) });
  }
  return out;
}

function uniqBy<T>(list: T[], key: (t: T) => string): T[] {
  const seen = new Set<string>();
  return list.filter((x) => !seen.has(key(x)) && (seen.add(key(x)), true));
}

/** Write public/catalog.json: every real operator plus its contact facts. The app fetches it at startup. */
export function syncCatalogToApp(): { path: string; count: number } {
  const rows = db
    .prepare(
      `SELECT id, domain, name, website, city, region, metro_id, family, icon_key, rating, review_count, origin, lat, lon
       FROM operators WHERE origin != 'demo' AND name IS NOT NULL AND length(name) >= 3
       ORDER BY completeness DESC, name ASC`,
    )
    .all() as CatalogRow[];
  const dead = new Set(
    (db.prepare(
      `SELECT o.id FROM operators o WHERE o.website IS NULL AND o.phone IS NULL
         AND NOT EXISTS (SELECT 1 FROM facts f WHERE f.operator_id = o.id AND f.fact_key = 'cover')
         AND NOT EXISTS (SELECT 1 FROM offerings x WHERE x.operator_id = o.id)`,
    ).all() as { id: string }[]).map((r) => r.id),
  );
  // A listing with no site, no phone, no photo and no menu gives a guest nothing to act on. Keep it for outreach only.
  const full = rows.filter((r) => !MARKETPLACES.test(r.domain) && !dead.has(r.id) && !NOT_EXPERIENCE.test(r.name)).map(toCatalogItem);
  console.log("Left out " + dead.size + " map-only rows with nothing a guest can use.");
  const contactByDomain: Record<string, OperatorContact> = {};
  for (const c of allContacts()) contactByDomain[c.domain] = c;

  // One small file per operator with everything: services, photos, videos, facts, contact.
  const dir = join(appDataDir, "../../public/o");
  mkdirSync(dir, { recursive: true });
  const keep = new Set<string>();
  for (const item of full) {
    const c = contactByDomain[String(item.src)];
    const contact = c
      ? { domain: c.domain, phone: c.phone, street: c.street, city: c.city, region: c.region, postal: c.postal, hours: c.hours }
      : undefined;
    const file = item.id + ".json";
    keep.add(file);
    writeFileSync(join(dir, file), JSON.stringify({ ...item, contact }));
  }
  for (const f of readdirSync(dir)) if (!keep.has(f)) unlinkSync(join(dir, f));

  // The browse catalog carries only what cards, rails and search need. Details load per listing.
  const operators = full.map((item) => {
    const options = (item.options as { price: number | null }[]) || [];
    const priced = options.map((o) => o.price).filter((n): n is number => n != null && n > 0);
    return {
      id: item.id, title: item.title, cat: item.cat, art: item.art, area: item.area, metroId: item.metroId, src: item.src,
      rating: item.rating, reviews: item.reviews, lat: item.lat, lon: item.lon, cover: item.cover, video: item.video,
      locations: item.locations,
      tags: ((item.tags as string[]) || []).slice(0, 6),
      from: priced.length ? Math.min(...priced) : undefined,
      dur: item.dur, fc: item.fc,
      options: [], specs: [], includes: [], gap: "", lite: true,
    };
  });
  const path = join(appDataDir, "../../public/catalog.json");
  writeFileSync(path, JSON.stringify({ generatedAt: new Date().toISOString(), operators, contacts: {} }));
  const pages = writeLandingPages(full as never);
  console.log("Wrote " + pages.pages + " landing pages to public/p");
  return { path, count: operators.length };
}
