import { mkdirSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CITIES } from "../discover/cities.ts";
import { db } from "../db/client.ts";
import { writeLandingPages } from "./pages.ts";
import { encodeWeek } from "./hours.ts";
import { claimKeyHash } from "../lib/claim.ts";
import { METROS, nearestMetro } from "../taxonomy/catalog.ts";
import { rankForCover } from "../enrich/photorelevance.ts";
import { existsSync, readFileSync as readFileSyncFs } from "node:fs";

/** A claimed operator's saved edits (public/profiles/<id>.json) win over what the crawl found. */
function profileOverlay(id: string): { published: boolean; patch: Record<string, unknown> } | null {
  const f = join(dirname(fileURLToPath(import.meta.url)), "../../../public/profiles", id + ".json");
  if (!existsSync(f)) return null;
  try {
    const rec = JSON.parse(readFileSyncFs(f, "utf8")) as { published?: boolean; patch?: Record<string, unknown> };
    return { published: rec.published !== false, patch: rec.patch || {} };
  } catch {
    return null;
  }
}

const here = dirname(fileURLToPath(import.meta.url));
const appDataDir = join(here, "../../../src/data");

/** Public contact facts for one operator. Every field is null when the site did not publish it. */
export type OperatorContact = {
  domain: string;
  website: string | null;
  phone: string | null;
  email: string | null;
  street: string | null;
  city: string | null;
  region: string | null;
  postal: string | null;
  hours: string[];
  bookingVendor: string | null;
  fetchedAt: string | null;
};

type Row = {
  domain: string;
  website: string | null;
  phone: string | null;
  email: string | null;
  street: string | null;
  city: string | null;
  region: string | null;
  postal: string | null;
  hours: string | null;
  hours_text: string | null;
  calendar_vendor: string | null;
  fetched_at: string | null;
};

export function contactFor(domain: string): OperatorContact | null {
  const row = db
    .prepare(
      `SELECT o.domain, o.website, o.phone, o.email, o.street, o.city, o.region, o.postal, o.hours, o.calendar_vendor,
              (SELECT MAX(fetched_at) FROM sources s WHERE s.operator_id = o.id AND s.http_status = 200) AS fetched_at
       FROM operators o WHERE o.domain = ?`,
    )
    .get(domain) as Row | undefined;
  return row ? toContact(row) : null;
}

export function allContacts(): OperatorContact[] {
  const rows = db
    .prepare(
      `SELECT o.domain, o.website, o.phone, o.email, o.street, o.city, o.region, o.postal, o.hours, o.calendar_vendor,
              (SELECT fact_value FROM facts f WHERE f.operator_id = o.id AND f.fact_key = 'hours_text' LIMIT 1) AS hours_text,
              (SELECT MAX(fetched_at) FROM sources s WHERE s.operator_id = o.id AND s.http_status = 200) AS fetched_at
       FROM operators o WHERE o.origin != 'demo' ORDER BY o.domain`,
    )
    .all() as Row[];
  return rows.map(toContact);
}

function toContact(r: Row): OperatorContact {
  return {
    domain: r.domain,
    website: r.website,
    phone: silent(r.phone),
    email: r.email,
    street: r.street,
    city: r.city,
    region: r.region,
    postal: r.postal,
    hours: tidyHours(r.hours ? r.hours.split(" | ") : r.hours_text ? [r.hours_text] : []),
    bookingVendor: r.calendar_vendor,
    fetchedAt: r.fetched_at,
  };
}

/**
 * Write src/data/contacts.ts for the hand-verified seed operators only. Everything else ships in public/catalog.json,
 * which the app fetches at startup, so the bundled file stays small.
 */
export function syncContactsToApp(): { path: string; count: number } {
  const seedDomains = new Set(
    (db.prepare("SELECT domain FROM operators WHERE origin IN ('seed', 'public_site')").all() as { domain: string }[]).map((r) => r.domain),
  );
  const contacts = allContacts().filter((c) => seedDomains.has(c.domain));
  const body = contacts
    .map((c) => "  " + JSON.stringify(c.domain) + ": " + JSON.stringify(c) + ",")
    .join("\n");
  const src = `import type { OperatorContact } from "./types";

/**
 * GENERATED by \`npm run backend:sync\`. Do not edit by hand.
 * Public contact facts per operator domain, copied from each company's own site by the backend scraper.
 * A null field means the site did not publish it. Do not fill gaps by hand.
 */
export const CONTACTS: Record<string, OperatorContact> = {
${body}
};
`;
  const path = join(appDataDir, "contacts.ts");
  writeFileSync(path, src);
  return { path, count: contacts.length };
}

/* ---------- Full catalog export for the guest app ---------- */

type CatalogRow = {
  id: string;
  domain: string;
  name: string;
  legal_name?: string | null;
  website: string | null;
  city: string | null;
  region: string | null;
  metro_id: string | null;
  family: string | null;
  icon_key: string;
  rating: number | null;
  review_count: number | null;
  origin: string;
  lat: number | null;
  lon: number | null;
};

/** Marketplaces and directories are not operators. They never belong in the catalog. */
/** Names the discovery net caught that are not something a guest books: car rentals, retail, festivals, museums, clubs, public piers. */
export const NOT_EXPERIENCE = /\bmurals?\b|\bcar rentals?\b|\brent-?a-?car\b|\b(thrifty|hertz|avis|enterprise|budget) \b|u-haul|\bauto rentals?\b|\bsports? shop\b|\bski sports\b|\bsporting goods\b|\bfestival\b|\bfair\b(?! ?winds)|\browing club\b|\byacht club\b|\bmunicipal pier\b|\bcommunity boathouse\b|\bboat ramp\b|\bpublic launch\b|\bstate park\b|\bcounty park\b/i;
export const MARKETPLACES = /(^|\.)(sailo|getmyboat|boatsetter|viator|tripadvisor|airbnb|expedia|groupon|yelp|peek|fareharbor|getyourguide|klook|eventbrite|meetup|facebook|instagram|booking|hotels|vrbo|kayak|tours4fun|musement|headout|goldstar|boatbound|clickandboat|samboat|fishingbooker|fishanywhere|guidesly)\.(com|net|co|io|ca)$/i;

/**
 * Opening hours worth showing: a weekly pattern with times, or "closed". Snapshots like "Open today 9am-5pm" and
 * "Hours This Week Thursday 2:00 PM-4:00 PM" describe one day the crawler happened to visit, so they are dropped.
 */
function tidyHours(lines: string[]): string[] {
  const out: string[] = [];
  for (const raw of lines) {
    let h = raw.replace(/^\s*hours(?: of operation| & admission)?\s*:?\s*/i, "").replace(/\s+/g, " ").trim();
    if (!h || SILENT.test(h)) continue;
    if (/\b(today|tonight|tomorrow|this week|open now|closed now|closes? (at|in)|opens? (at|in)|until \d)\b/i.test(h)) continue;
    if (/\b(january|february|march|april|may|june|july|august|september|october|november|december)\s+\d/i.test(h)) continue;
    const hasDay = /\b(mon|tue|wed|thu|fri|sat|sun)[a-z]*\b|\b(daily|every ?day|7 days|weekdays?|weekends?|seasonal|year[- ]round)\b/i.test(h);
    const hasTime = /\d{1,2}(:\d{2})?\s*(am|pm|a\.m\.|p\.m\.)|\d{1,2}:\d{2}|\bclosed\b|\b24 hours\b|dawn|dusk|sunrise|sunset/i.test(h);
    if (!(hasDay && hasTime) && !/\b(by appointment|reservation only|on request)\b/i.test(h)) continue;
    if (h.length > 140) h = h.slice(0, 140).replace(/\s+\S*$/, "");
    if (!out.includes(h)) out.push(h);
    if (out.length >= 7) break;
  }
  return out;
}

const DEFAULT_GAP = "Prices, hours and eligibility are not copied here yet. We will ask when you request.";

/** A chain's other venues, for nearest-location distance. Empty for the usual single-site operator. */
function extraLocations(operatorId: string): { city: string; region?: string; lat: number; lon: number; street?: string }[] | undefined {
  const rows = db
    .prepare("SELECT city, region, street, lat, lon FROM locations WHERE operator_id = ? ORDER BY city LIMIT 60")
    .all(operatorId) as { city: string | null; region: string | null; street: string | null; lat: number; lon: number }[];
  if (!rows.length) return undefined;
  return rows.map((l) => ({ city: l.city || "Nearby", region: l.region || undefined, lat: Math.round(l.lat * 1e4) / 1e4, lon: Math.round(l.lon * 1e4) / 1e4, street: l.street || undefined }));
}

/** "Deer Harbor Charters" and "DEER HARBOR CHARTERS LLC" are one business. */
function titleKey(t: string): string {
  return t.toLowerCase().replace(/\b(llc|inc|ltd|co|corp|company)\b/g, "").replace(/[^a-z0-9]+/g, " ").trim();
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
}

/**
 * How many other operator domains publish the same image file. A theme's own placeholder, a parked-domain banner
 * and a photo library's sailboat all turn up on sites that have nothing to do with each other, and a photo like
 * that is the one thing we can prove is not this operator's. Counted once per process, over the whole catalog.
 */
let reuseByUrl: Map<string, number> | null = null;
function photoReuse(): Map<string, number> {
  if (!reuseByUrl) {
    reuseByUrl = new Map();
    const rows = db
      .prepare(
        `SELECT f.fact_value AS url, COUNT(DISTINCT o.domain) AS n FROM facts f
         JOIN operators o ON o.id = f.operator_id
         WHERE f.fact_key IN ('photo', 'cover') GROUP BY f.fact_value HAVING n > 1`,
      )
      .all() as { url: string; n: number }[];
    for (const row of rows) reuseByUrl.set(row.url, row.n - 1);
  }
  return reuseByUrl;
}

/** One operator in the shape the guest app's Unclaimed type expects. Facts only, nothing invented. */
export function toCatalogItem(r: CatalogRow): Record<string, unknown> {
  const rawOfferings = db
    .prepare("SELECT name, detail, duration, price_cents, price_unit, source_url FROM offerings WHERE operator_id = ? ORDER BY price_cents IS NULL, price_cents")
    .all(r.id) as { name: string; detail: string | null; duration: string | null; price_cents: number | null; price_unit: string | null; source_url: string | null }[];
  const rawFacts = db.prepare("SELECT fact_key, fact_value, source_url FROM facts WHERE operator_id = ?").all(r.id) as { fact_key: string; fact_value: string; source_url: string | null }[];
  // The operator's own pages: the catalog domain, the website field's host (sister brand or a second domain),
  // and site-builder hosts they publish on (mammothpack.wixsite.com is still mammothpack).
  const trusted = (url: string | null) => sourceIsOwn(url, r.domain) || (r.website ? sourceIsOwn(url, hostOf(r.website)) : false) || sameBrand(url, r.domain);
  const offCity = (url: string | null) => sourceIsAnotherTown(url, r.city, r.metro_id);
  // Rows the audit showed to be noise: another business's page, another town's branch, merch, "not stated" filler, stale or junk lines.
  // A chain's pricing page often sits under another branch's path (/vaughan/hours-pricing on the Mississauga record).
  // Same-branch rows win; other-branch rows fill in only when this branch has none, since chain menus are shared.
  const own = rawOfferings.filter((o) => trusted(o.source_url));
  const onSite = own.some((o) => !offCity(o.source_url)) ? own.filter((o) => !offCity(o.source_url)) : own;
  const isMerch = (o: { name: string; detail: string | null; source_url?: string | null }) => MERCH.test(o.name + " " + (o.detail || "")) || /\/(merch|shop|apparel)(\/|$)/i.test((o.source_url || "").replace(/^https?:\/\/[^/]+/, "")) || (SPIRITS.test(o.name) && !/tasting|tour|flight|class|experience|pairing|session/i.test(o.name + " " + (o.detail || "")));
  const merchCount = onSite.filter(isMerch).length;
  // A menu that is nothing but products is a shop, not an experience menu. Otherwise keep the bookable rows and drop the merch.
  const offerings = (merchCount > 0 && merchCount === onSite.length ? [] : onSite.filter((o) => !isMerch(o)))
    .filter((o) => !RESELLER.test(o.name + " " + (o.detail || "")))
    .filter((o) => !FILTER_LABEL.test(o.name))
    // A taproom's "Food $4" or "Beer $7.50" is a menu category, not something a guest books a time for.
    .filter((o) => !(MENU_CATEGORY.test(o.name) && (o.price_cents == null || o.price_cents < 3000)))
    // A $1 line is a deposit, a token or a placeholder; a $19,995 line is a boat for sale. Neither is a price a guest pays here.
    .filter((o) => !isForSale(o))
    .map((o) => ({ ...o, name: collapseRepeats(fixShouting(trimWords(o.name, 70))), price_cents: o.price_cents != null && o.price_cents < 200 ? null : o.price_cents }))
    .filter((o, i, a) => a.findIndex((x) => x.name.toLowerCase() === o.name.toLowerCase() && x.price_cents === o.price_cents && (x.duration || x.detail || "") === (o.duration || o.detail || "")) === i)
    .map((o) => ({ ...o, price_unit: fixUnit(o) }));
  const title = cleanTitle(decodeEntities(r.name), { city: r.city, region: r.region, legalName: r.legal_name });
  const keysWithOwnBranch = new Set(rawFacts.filter((f) => trusted(f.source_url) && !offCity(f.source_url)).map((f) => f.fact_key));
  const facts = rawFacts.filter((f) => {
    if (/^(photo|cover|video|video_embed|yt_video|tiktok_profile|social:)/.test(f.fact_key)) return true;
    if (!trusted(f.source_url)) return false;
    if (offCity(f.source_url) && keysWithOwnBranch.has(f.fact_key)) return false;
    if (TEXT_KEYS.test(f.fact_key)) {
      const v = f.fact_value;
      if (GAP_LINE.test(v) || JUNK_LINE.test(v) || RETAIL_LINE.test(v) || STALE_LINE.test(v)) return false;
    }
    return true;
  });
  const pick = (k: string) => facts.filter((f) => f.fact_key === k).map((f) => (/^(photo|video|yt_video|social:)/.test(k) ? f.fact_value : decodeEntities(f.fact_value)));
  // Booking-widget item photos are the operator's own curated product shots. They beat whatever the crawl scored highest.
  const widgetPhotos = uniq(facts.filter((f) => f.fact_key === "photo" && /fareharbor|xola|filestack/i.test((f.source_url || "") + " " + f.fact_value)).map((f) => f.fact_value));
  const art = artFromName(r.name, r.icon_key);
  /**
   * Cover choice, re-derived from facts we already hold. The order below is the order this function used to
   * publish, so the widget shots still lead and a tie changes nothing; `rankForCover` only moves a photo up when
   * its file name, the page it came from or the booking item it illustrates says more about this business than the
   * one above it. The alt text is the one signal the facts table does not keep, so the crawl scores that itself.
   * Nothing is dropped: the rest stay in the gallery. This is why a better cover does not need a re-crawl.
   */
  const photoPage = new Map<string, string>();
  for (const f of facts) if ((f.fact_key === "photo" || f.fact_key === "cover") && f.source_url && !photoPage.has(f.fact_value)) photoPage.set(f.fact_value, f.source_url);
  const photoItem = new Map<string, string>();
  for (const raw of pick("service_photo")) {
    try {
      const d = JSON.parse(raw) as { name: string; url: string };
      if (d.url && !photoItem.has(d.url)) photoItem.set(d.url, d.name);
    } catch {
      /* ignore */
    }
  }
  // Every other photo from a booking widget came off one item's page, so that item names it too.
  const itemByPage = new Map<string, string>();
  for (const o of rawOfferings) if (o.source_url && !itemByPage.has(o.source_url)) itemByPage.set(o.source_url, o.name);
  const ranked = rankForCover(
    uniq([...widgetPhotos, ...pick("cover"), ...pick("photo")].filter(isPhotoName)).map((url) => ({
      url,
      page: photoPage.get(url) || null,
      item: photoItem.get(url) || itemByPage.get(photoPage.get(url) || "") || null,
      curated: WIDGET_HOSTS.test(url),
      reuse: photoReuse().get(url) || 0,
    })),
    { title, art, family: r.family || "water" },
  ).map((p) => fullSize(p.url) || "");
  const area = r.city ? (r.region && !r.city.includes(r.region) ? r.city + ", " + r.region : r.city) : r.region || "";
  return {
    id: "o-" + slug(r.domain),
    claimKey: claimKeyHash("o-" + slug(r.domain)),
    title,
    cat: r.family || "water",
    art,
    area,
    metroId: metroFor(r),
    src: r.domain,
    rating: r.rating ?? undefined,
    reviews: r.review_count ?? undefined,
    specs: uniq([...pick("spec"), ...pick("requirement"), ...pick("group")].map(cleanLine)).filter(isTidyLine).slice(0, 10),
    options: offerings.map((o) => ({
      name: o.name,
      detail: silent(o.duration) || silent(o.detail) || "",
      price: o.price_cents == null ? null : o.price_cents / 100,
      per: o.price_unit && o.price_unit.startsWith("/") ? o.price_unit : undefined,
    })),
    services: (() => {
      const descs = new Map<string, string>();
      for (const raw of pick("service_desc")) {
        try {
          const d = JSON.parse(raw) as { name: string; desc: string };
          descs.set(d.name.toLowerCase(), scrubDesc(d.name, d.desc));
        } catch {
          /* ignore */
        }
      }
      const photos = new Map<string, string>();
      for (const raw of pick("service_photo")) {
        try {
          const d = JSON.parse(raw) as { name: string; url: string };
          photos.set(d.name.toLowerCase(), d.url);
        } catch {
          /* ignore */
        }
      }
      const groups = new Map<string, { name: string; desc: string | null; photo?: string; variants: { label: string; price: number | null; per?: string; optionIdx: number }[] }>();
      offerings.forEach((o, idx) => {
        const key = o.name.toLowerCase();
        if (NOT_A_SERVICE.test(o.name)) return;
        const g = groups.get(key) || { name: o.name, desc: descs.get(key) || null, photo: fullSize(photos.get(key) || "") || undefined, variants: [] };
        g.variants.push({
          label: silent(o.duration) || silent(o.detail) || "Standard",
          price: o.price_cents == null ? null : o.price_cents / 100,
          per: o.price_unit && o.price_unit.startsWith("/") ? o.price_unit : undefined,
          optionIdx: idx,
        });
        groups.set(key, g);
      });
      return [...groups.values()].filter((g) => !/gift ?cards?|gift certificate|deposit|membership|season pass/i.test(g.name)).slice(0, 14);
    })(),
    // "Private Ride for Two: up to 1 guests per booking" is a group cap, and "What to Bring: ..." belongs under bring.
    includes: uniq(pick("includes").map(cleanLine)).filter(isTidyLine).filter((l) => !/gift ?card|gift certificate|will be provided upon|directions will|upon purchas|up to \d+ guests? per booking|minimum \d+ guests? per booking|^what to bring\b/i.test(l)).slice(0, 10),
    addons: pick("addon")
      .map((a) => {
        const m = a.match(/^(.*?)\s*\$(\d+(?:\.\d+)?)$/);
        return m ? { name: m[1].trim().replace(/\s+(for|at|only|just|from|is)$/i, ""), detail: "", price: Number(m[2]) } : null;
      })
      .filter((a): a is { name: string; detail: string; price: number } => !!a)
      // "An additional $35" is a fee sentence, not something a guest adds to a cart.
      .filter((a) => a.name.length >= 3 && !/^(an?|the|plus|extra|additional|only|just|from|starting|starts|add|adds|is|are|and|or|for)\b/i.test(a.name) && !/\b(fee|surcharge|deposit|tax|gratuity|tip|per person|per hour)\b/i.test(a.name))
      .slice(0, 6),
    // The honest gap line. Once the widget or crawl gave real rules and policies, say those instead of "not copied yet".
    gap: pick("published_gap")[0] || pick("cancellation")[0] || (pick("policy").length || pick("requirement").length ? [...pick("policy")].slice(0, 3).join(" ") || "Ask the operator about cancellations." : DEFAULT_GAP),
    blurb: (() => {
      // The first source whose text survives cleaning wins: a description that is all headings falls through to the meta line.
      const b = [pick("description")[0], pick("site_desc")[0], pick("one_line")[0]].map((raw) => cleanBlurb(raw || "", { title, city: r.city, region: r.region })).find(Boolean) || "";
      return b && !/\b(purchase|shop|buy) (boards|paddles|gear|apparel|merch)/i.test(b) ? b : undefined;
    })(),
    cover: ranked.find(Boolean) || undefined,
    photos: uniq(ranked).slice(0, 10),
    ytVideos: pick("yt_video")
      .map((raw) => {
        try {
          const v = JSON.parse(raw) as { id: string; title: string; views: number };
          return { id: v.id, title: v.title, views: v.views };
        } catch {
          return null;
        }
      })
      .filter((v): v is { id: string; title: string; views: number } => !!v)
      .slice(0, 3),
    tiktok: pick("tiktok_profile")[0] || undefined,
    instagram: pick("social:instagram")[0] || undefined,
    video: pick("video")[0] || undefined,
    videoEmbed: pick("video_embed")[0] || undefined,
    lat: r.lat ?? undefined,
    lon: r.lon ?? undefined,
    locations: extraLocations(r.id),
    tags: uniq([...pick("google_category"), ...pick("service"), ...offerings.map((o) => o.name)].map((t) => collapseRepeats(fixShouting(t)))).filter((t) => !NOT_A_SERVICE.test(t) && !NAV_LABEL.test(t)).slice(0, 12),
    extraNote: [...pick("extra").slice(0, 1), ...pick("policy"), ...pick("checkin"), ...pick("meeting_point"), ...pick("season")].filter((l) => !SILENT.test(l)).join(" · ").slice(0, 700) || undefined,
    // Viator-shaped sections. Each only appears when the site said it.
    highlights: collapseRules(uniq(pick("spec").map(cleanLine)).filter(isTidyLine).filter((l) => !/^what to bring\b|you are required to bring/i.test(l))).slice(0, 8),
    requirements: collapseRules(uniq(pick("requirement").map(cleanLine)).filter(isTidyLine)).slice(0, 10),
    groupInfo: uniq(pick("group").map(cleanLine)).filter(isTidyLine).slice(0, 5),
    bring: uniq([...pick("bring"), ...[...pick("spec"), ...pick("includes")].filter((l) => /^what to bring\b/i.test(l)).map((l) => l.replace(/^what to bring[:\s-]*/i, ""))].map(cleanLine)).filter(isTidyLine).slice(0, 8),
    season: silent(cleanLine(pick("season")[0] || "")) || undefined,
    meetingPoint: cleanLine(pick("meeting_point")[0] || "") || undefined,
    checkin: cleanPara(pick("checkin")[0] || "") || undefined,
    cancellation: dropSilent(cleanPara(pick("cancellation")[0] || "")) || dropSilent(cleanPara(pick("policy").filter((l) => /cancel|refund/i.test(l)).join(" "))) || undefined,
    policies: uniq(pick("policy").map(cleanLine)).filter(isTidyLine).filter((l) => !/gift ?card|gift certificate/i.test(l)).slice(0, 8),
    waiverUrl: pick("waiver_url").find((u) => /^https?:\/\/\S+$/.test(u) && !/\/w\/?$/.test(u)) || undefined,
    hoursText: uniq([...pick("hours_text"), ...pick("hours")].flatMap((h) => h.split(/\s*\|\s*/)).map((h) => cleanLine(h.replace(/^hours(?: & admission)?\s*/i, ""))).filter((h) => h.length > 3 && !/not stated/i.test(h) && HAS_TIME.test(h) && !/[ap]m[A-Za-z]/.test(h))).slice(0, 7),
    faq: uniqBy(pick("faq").flatMap(parseFaqs), (f) => f.q.toLowerCase()).slice(0, 8),
    quotes: pick("review")
      .map((raw) => {
        try {
          const r = JSON.parse(raw) as { a: string | null; r: number | null; t: string; d: string | null };
          // "Liz S. | Yelp" keeps the name; the platform becomes the date slot when there is no date.
          const parts = (r.a || "").split(/\s*[|·,]\s*/);
          let author = parts[0]?.trim() || "";
          // A sentence caught as a name ("Highly recommend booking today!") is not a name.
          if (/[!?.]$/.test(author) || author.split(/\s+/).length > 5 || /\b(recommend|amazing|great|best|love|thank)\b/i.test(author)) author = "";
          const via = parts.slice(1).find((x) => /yelp|tripadvisor|google|facebook|airbnb|viator|expedia/i.test(x));
          return { author: author || undefined, rating: r.r || undefined, text: r.t, date: r.d || (via ? "via " + via.trim() : undefined) };
        } catch {
          return null;
        }
      })
      .filter((r) => !!r && r.text.length >= 30)
      .map((r) => r as { author?: string; rating?: number; text: string; date?: string })
      .slice(0, 6),
    dur: durationOf(offerings.map((o) => o.duration || o.detail || "")) || undefined,
    fc: freeCancel(cleanPara(pick("cancellation")[0] || "") || pick("policy").filter((l) => /cancel|refund/i.test(l)).join(" ")) || undefined,
    // Day-specific deals the site states, as written (scripts/promo-crawl.mts). Never invented.
    promos: facts
      .filter((f) => f.fact_key === "promo")
      .map((f): { text: string; days: number[]; start?: string; end?: string } | null => {
        try {
          const p = JSON.parse(f.fact_value) as { text: string; days: number[]; start?: string; end?: string };
          return typeof p.text === "string" && Array.isArray(p.days) ? { text: decodeEntities(p.text), days: p.days, start: p.start, end: p.end } : null;
        } catch {
          return null;
        }
      })
      .filter((p): p is { text: string; days: number[]; start?: string; end?: string } => !!p && p.text.length <= 160)
      .filter((p, i, a) => a.findIndex((x) => x.text.toLowerCase() === p.text.toLowerCase()) === i)
      .slice(0, 8),
  };
}

/** "2 hours", "90 min", "1 to 4 hours": the first duration the menu states. */
function durationOf(texts: string[]): string | null {
  for (const t of texts) {
    const m = t.match(/\b(\d+(?:\.\d+)?)\s*(?:-|to)?\s*(\d+)?\s*(hours?|hrs?|minutes?|mins?|days?)\b/i);
    if (!m) continue;
    const n = Number(m[2] || m[1]);
    if (/notice|advance|prior|before|cancel|refund/i.test(t)) continue;
    const isMin = /min/i.test(m[3]);
    const isDay = /day/i.test(m[3]);
    // A booking is minutes to a day or two. Anything longer is a policy window that leaked into the menu text.
    if ((isMin && n > 600) || (!isMin && !isDay && n > 14) || (isDay && n > 7)) continue;
    const unit = isMin ? "min" : isDay ? (n === 1 ? "day" : "days") : n === 1 ? "hour" : "hours";
    return (m[2] ? m[1] + " to " + m[2] : m[1]) + " " + unit;
  }
  return null;
}

/** "Free cancellation up to 48 hours before", only when the operator's own words promise a full refund. */
function freeCancel(text: string): string | null {
  if (!text || !/full refund|free cancellation|100% refund|fully refundable/i.test(text)) return null;
  if (/non-?refundable|no refunds?\b/i.test(text) && !/full refund/i.test(text)) return null;
  const m = text.match(/(\d+)\s*(hours?|hrs?|days?)/i);
  if (!m) return "Free cancellation";
  const n = Number(m[1]);
  const unit = /day/i.test(m[2]) ? (n === 1 ? "day" : "days") : n === 1 ? "hour" : "hours";
  return "Free cancellation up to " + n + " " + unit + " before";
}

/** "Hawaiian Parasail" is parasailing whatever OpenStreetMap tagged it. The name wins when it names the activity outright. */
const ART_BY_NAME: [RegExp, string][] = [
  // Airboat, swamp and whale-watching outfits are tours, not sunset sails.
  [/airboat|swamp|alligator|gator|everglades|whale watch|dolphin watch|glass ?bottom/i, "tour"],
  [/\bparasail/i, "parasail"],
  [/\bjet ?ski|waverunner|sea-?doo/i, "jetski"],
  [/\bskydiv|\btandem jump|\bparachut/i, "skydive"],
  [/\baxe|\bhatchet/i, "axe"],
  [/\bescape (room|game)|\bescape\b/i, "escape"],
  [/\bkart|\bkarting/i, "kart"],
  [/\bpaintball|\bairsoft|\blaser tag/i, "paintball"],
  [/\bhelicopter|\bheli\b|\bhelitour/i, "heli"],
  [/\bballoon/i, "balloon"],
  [/\bkayak|\bpaddle ?board|\bcanoe|\bsup\b|\bpaddl/i, "kayak"],
  [/\bpontoon/i, "pontoon"],
  [/\bhorse|\bequestrian|\btrail ride|\bstable/i, "horse"],
  [/\bfishing|\bcharter fish|\bsportfish|\bangl/i, "fishing"],
  [/\bsunset (cruise|sail)|\bcruise|\bsailing|\bcatamaran|\byacht/i, "cruise"],
];
function artFromName(name: string, fallback: string): string {
  for (const [re, art] of ART_BY_NAME) if (re.test(name)) return art;
  return fallback;
}

/* ---------- audit-driven filters (9 Sept 2026 data QA) ---------- */

const WIDGET_HOSTS = /fareharbor|xola|peek\.com|bookeo|rezdy|checkfront|filestack|resova|fareharbor/i;
const TEXT_KEYS = /^(requirement|policy|bring|meeting_point|group|includes|spec|cancellation|checkin|faq|hours_text|season|description|one_line|site_desc)$/;
const GAP_LINE = /\b(not (stated|specified|mentioned|listed|published|provided|available on)|no specific .* (stated|listed|mentioned)|^not stated$|no information (available|provided))\b/i;
const JUNK_LINE = /\b(call|contact|phone|email)( us)? (for|to)\b|\bsee (the |our )?faq|\bclick here|\bprint and color|\bsubscribe|\bnewsletter|\bfollow us|\bcookie|\bprivacy policy|\bterms (of|and) (service|use|conditions)|all rights reserved|©|\bcopyright\b|\bconsent to (the use|cookies|tracking)|\benable javascript|\bjavascript\b|\baccept all\b|\bopt[- ]?out\b|\bpowered by\b|\bwebsite by\b|\bskip to (main )?content|\btoggle (menu|navigation)/i;
const RETAIL_LINE = /\b(restocking|rma\b|return shipping|return merchandise|free shipping|ships? within|shipping (cost|rate|polic)|in-?store pickup|wholesale)\b/i;
const STALE_LINE = /\b20(1\d|2[0-5])\b|\bcovid|\bcoronavirus|\bpandemic/i;
/** Menu headings a taproom or restaurant page lists with a starting price. */
const MENU_CATEGORY = /^(?:food|foods|beer|beers|drafts?|draught|on tap|wine|wines|cocktails?|drinks?|beverages?|snacks?|appetizers?|starters?|small plates|shareables?|entrees?|mains?|desserts?|sides?|salads?|sandwiches?|burgers?|pizzas?|tacos?|brunch|lunch|dinner|breakfast|coffee|tea|kids menu|happy hour|cans?|bottles?|growlers?|crowlers?|flights?|pints?|merch|retail)$/i;
/** Site filter chips scraped as products: "Most Immersive", "Hardest", "Biggest Game", "Best Sellers", "All". */
const FILTER_LABEL = /^(?:(?:the )?(?:most|least|second|third) \w+|hardest|easiest|scariest|biggest|smallest|newest|oldest|thrilling|abstract|immersive|popular|featured|trending|best ?sellers?|top ?rated|all|other|more|filter|sort|view all|see all|\d+ floor \w+)$/i;

/** Things sold through the operator's site that are someone else's product: theme-park tickets, tool rentals, package deals. */
const RESELLER = /\b(park (child|adult|hopper)|day hopper|\bhopper\b|park tickets?|disney|universal studios|seaworld|legoland|busch gardens|pole pruner|chainsaw|generator|excavator|lawn ?mower|tiller|pressure washer|storage unit|u-?haul)\b/i;

/**
 * The metro a listing shows under. Discovery assigned metros by name match or a 160 km radius, which put Montreal, VT
 * in Montreal, Sheffield, PA in Niagara and a Charlotte pub crawl in Austin. Now: the nearest metro within 80 km of the
 * pin (100 km when it is the one discovery chose); a pin far from the address city is ignored; with no pin, the stored
 * metro stays unless the address state has metros of its own and this one is nowhere near them. Otherwise none.
 */
const METRO_KM = 80;
const METRO_KM_KEEP = 100;
/**
 * Metros whose market is wider than 80 km from the pin. Detroit covers Windsor and Ann Arbor, Niagara covers Buffalo,
 * St. Catharines and Hamilton on both sides of the border; the flat radius cut each by a third.
 */
const METRO_REACH: Record<string, number> = { detroit: 130, niagara: 130 };
const reachOf = (id: string) => METRO_REACH[id] || METRO_KM;
const keepOf = (id: string) => Math.max(METRO_KM_KEEP, METRO_REACH[id] || 0);
function kmBetween(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const d = Math.PI / 180;
  const a = Math.sin(((lat2 - lat1) * d) / 2) ** 2 + Math.cos(lat1 * d) * Math.cos(lat2 * d) * Math.sin(((lon2 - lon1) * d) / 2) ** 2;
  return 2 * 6371 * Math.asin(Math.sqrt(a));
}
function metroFor(r: { metro_id: string | null; region: string | null; city: string | null; lat: number | null; lon: number | null }): string {
  const stored = r.metro_id ? METROS.find((m) => m.id === r.metro_id) : null;
  const region = r.region && r.region.length === 2 ? r.region.toUpperCase() : null;
  if (r.lat != null && r.lon != null) {
    // K1 Speed Tampa is pinned at head office in California: when we know where the address city is and the pin is
    // nowhere near it, the pin is wrong and the address decides. Arlington, VA under DC keeps its pin.
    const known = r.city && region ? CITIES.find((c) => c.region === region && c.name.toLowerCase() === r.city!.toLowerCase()) : null;
    const pinFitsAddress = !known || kmBetween(r.lat, r.lon, known.lat, known.lon) <= METRO_KM;
    if (!pinFitsAddress) return known && stored && kmBetween(known.lat, known.lon, stored.lat, stored.lon) <= METRO_KM ? stored.id : "";
    const near = nearestMetro(r.lat, r.lon, Math.max(...Object.values(METRO_REACH), METRO_KM));
    if (near && kmBetween(r.lat, r.lon, near.lat, near.lon) <= reachOf(near.id)) return near.id;
    // Outer suburbs (Newport, RI under Boston at 87 km) stay; Montreal, VT at 119 km from Montreal, QC does not.
    if (stored && kmBetween(r.lat, r.lon, stored.lat, stored.lon) <= keepOf(stored.id)) return stored.id;
    return "";
  }
  // No pin: trust discovery unless the address state is clearly somewhere else (a metro of that state exists, none near this one).
  if (!stored) return "";
  if (!region || stored.region === region) return stored.id;
  const stateMetros = METROS.filter((m) => m.region === region);
  return !stateMetros.length || stateMetros.some((m) => kmBetween(stored.lat, stored.lon, m.lat, m.lon) <= 2.5 * METRO_KM) ? stored.id : "";
}

/** US states, DC and territories, and Canadian provinces. Anything else is outside the market. */
const NA_REGION = /^(?:AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC|PR|VI|GU|AB|BC|MB|NB|NL|NS|NT|NU|ON|PE|QC|SK|YT)$/;
/** A pin inside the US or Canada: the mainland box, Alaska, or Hawaii. Cappadocia, Cairns and Vilnius fall outside. */
function inNorthAmerica(lat: number, lon: number): boolean {
  if (lat >= 24 && lat <= 50 && lon >= -125.5 && lon <= -66) return true; // contiguous US and southern Canada
  if (lat >= 41 && lat <= 84 && lon >= -141 && lon <= -52) return true; // Canada
  if (lat >= 51 && lat <= 72 && lon >= -180 && lon <= -129) return true; // Alaska
  if (lat >= 18.5 && lat <= 22.5 && lon >= -160.5 && lon <= -154.5) return true; // Hawaii
  if (lat >= 17.5 && lat <= 18.6 && lon >= -67.5 && lon <= -64.5) return true; // Puerto Rico and the Virgin Islands
  return false;
}
/** Titles that name the activity and nothing else: "Axe Throwing", "The Studio", "Garage". A guest cannot tell who it is. */
const GENERIC_TITLE = /^(?:the studio|(?:axe throwing|escape rooms?|bowling|bowl|golf(?: course| club)?|spa|yoga|pottery|cooking class(?:es)?|brewery|winery|paintball|go[- ]?karts?|mini ?golf|arcade|trampoline park|laser tag|garage|studio|gym|fitness|dance studio|museum|gallery|theat(?:re|er)|campground|marina|park|club|lounge|bar|pub|range|rink|pool|lake|beach|tours?|rentals?|charters?|adventures?|experiences?))$/i;

/** Words that are a site's navigation, not something a guest books: they never belong in a menu, a tag or a title. */
const NAV_LABEL = /^(?:home|homepage|welcome|contact(?: us)?|book(?: now| online)?|about(?: us)?|menu|reviews?|faqs?|gallery|photos|blog|news|events?|shop|store|login|sign ?in|cart|checkout|search|learn more|read more|more info|click here|call(?: us)?|email(?: us)?|directions|locations?|hours|pricing|prices|rates|specials|careers|jobs|employment|privacy policy|terms|terms of service|sitemap|donate|membership|subscribe|newsletter|reserve|reservations?|get tickets|buy tickets|tickets|gift ?cards?|gift certificates?)$/i;

/** A published opening line must carry a time, a "closed", or an appointment note; "Monday –" alone is a fragment. */
const HAS_TIME = /\d{1,2}(:\d{2})?\s*(a|p)\.?m\b|\d{1,2}:\d{2}|\bclosed\b|\b24 hours\b|\bnoon\b|\bmidnight\b|dawn|dusk|sunrise|sunset|by appointment|reservation only|on request/i;

/**
 * Photo file names that are documents, not photographs: scanned booklet pages (pg01.jpg, p2.png), screen shots,
 * schedules, menus, price lists, can mockups, logos and wordmarks, theme placeholders (dummy.png, og-default.jpg,
 * 700x400.png) and page chrome. Mirrors the harvest-time BAD_NAME in enrich/images.ts so a sync cleans photos the
 * crawl already stored. Widget photos (filestack, fareharbor) have opaque names and pass through.
 */
const DOC_PHOTO = /(?:^|[\/_\-. ])(?:pg|page|scan|doc)[-_]?\d{1,4}(?=[_\-.]|$)|^p\d{1,2}\.|\bpage[-_]?\d|booklet|\bscan(?:ned|s)?\b|document|\bpdf\b|certificate|\bcert\b|brochure|flyer|\bposter|infographic|(?:^|[\/_\-. ])menus?\d*(?=[\/_\-. (]|$)|menu-board|price[-_]?list|\brates?[-_.]|schedule|screen[-_ ]?shot|dummy|placeholder|og-default|^default[-_.]|^\d{3,4}x\d{3,4}(?:[-_]\d+)?\.(?:jpe?g|png|webp)$|mock-?ups?|mask[-_]?group|wordmark|lettermark|lockup|(?:^|[\/_\-. ])logo|newsletter|cartoon|clip-?art|illustration|graphics?\b|floor[-_]?plan|course[-_]?layout|(?:^|[\/_\-. ])layout(?=[\/_\-.]|$)|removebg|divider|spacer|qr[-_]?code|(?:^|[\/_\-. ])qr(?=[\/_\-. ]|$)|thank[-_ ]?you|(?:^|[\/_\-. ])sorry(?=[\/_\-. ]|$)|\bcoupon|voucher|sitemap|(?:^|[\/_\-. ])maps?(?=[\/_\-. ]|$)|favicon|apple-touch/i;
export function isPhotoName(url: string): boolean {
  if (!url) return false;
  let name = url.split("?")[0].split("/").slice(-1)[0];
  try {
    name = decodeURIComponent(name);
  } catch {
    /* keep the raw name */
  }
  return !DOC_PHOTO.test(name);
}

/** A boat, a cabin or a car with a sticker price was scraped from a dealer page on the operator's site. */
function isForSale(o: { name: string; detail: string | null; price_cents: number | null }): boolean {
  if (o.price_cents == null) return false;
  const text = (o.name + " " + (o.detail || "")).toLowerCase();
  if (o.price_cents > 2500000) return true;
  if (o.price_cents > 500000) return !/charter|yacht|private|group|wedding|event|package|week|weekend|multi|day|night|hour|tour|retreat|expedition|camp\b/.test(text);
  return /\b(for sale|msrp|sold|financing|dealer|pre-?owned|used boat|new boat|stock #|hull id|\d{4} (sea ?ray|yamaha|bayliner|tracker|bennington|malibu|mastercraft|lund|ranger|boston whaler))\b/i.test(text);
}

const SITE_WORDS = /^(?:home|homepage|welcome|official (?:site|website|home ?page)|website|site|online|book(?:ing)? online|book now|reservations?|home ?page|index|main)$/i;
/** Who a title belongs to, so a location tail ("at Clearwater Beach", "- Tampa Bay") can be told from a name ("The Legacy at Green Hills"). */
export type TitleContext = { city?: string | null; region?: string | null; legalName?: string | null };

const STATE_NAMES: Record<string, string> = {
  AL: "Alabama", AK: "Alaska", AZ: "Arizona", AR: "Arkansas", CA: "California", CO: "Colorado", CT: "Connecticut", DE: "Delaware", FL: "Florida", GA: "Georgia",
  HI: "Hawaii", ID: "Idaho", IL: "Illinois", IN: "Indiana", IA: "Iowa", KS: "Kansas", KY: "Kentucky", LA: "Louisiana", ME: "Maine", MD: "Maryland",
  MA: "Massachusetts", MI: "Michigan", MN: "Minnesota", MS: "Mississippi", MO: "Missouri", MT: "Montana", NE: "Nebraska", NV: "Nevada", NH: "New Hampshire", NJ: "New Jersey",
  NM: "New Mexico", NY: "New York", NC: "North Carolina", ND: "North Dakota", OH: "Ohio", OK: "Oklahoma", OR: "Oregon", PA: "Pennsylvania", RI: "Rhode Island", SC: "South Carolina",
  SD: "South Dakota", TN: "Tennessee", TX: "Texas", UT: "Utah", VT: "Vermont", VA: "Virginia", WA: "Washington", WV: "West Virginia", WI: "Wisconsin", WY: "Wyoming", DC: "District of Columbia",
  PR: "Puerto Rico", AB: "Alberta", BC: "British Columbia", MB: "Manitoba", NB: "New Brunswick", NL: "Newfoundland", NS: "Nova Scotia", NT: "Northwest Territories", NU: "Nunavut", ON: "Ontario",
  PE: "Prince Edward Island", QC: "Quebec", SK: "Saskatchewan", YT: "Yukon",
};
const STATE_BY_NAME: Map<string, string> = new Map(Object.entries(STATE_NAMES).map(([code, name]) => [name.toLowerCase(), code]));
const CITY_NAMES: Set<string> = new Set(CITIES.map((c) => c.name.toLowerCase()));
/** Words that turn a city into a place phrase rather than a brand: "Clearwater Beach", "Downtown Tampa", "Greater Toronto Area". */
const GEO_WORDS = /^(?:beach|beaches|bay|island|islands|key|keys|county|springs|harbor|harbour|lake|valley|coast|shores?|park|city|falls|heights|hills|point|cove|cape|river|pass|metro|area|downtown|greater|north|south|east|west|central|upper|lower|gulf|the|of|and|&|region|peninsula|sound|inlet|marina|pier|waterfront|resort)$/i;
/** Words a title keeps lower case unless they open it. */
const SMALL_WORDS = /^(?:a|an|and|at|by|for|from|in|of|on|or|the|to|with|de|du|le|del|von|van|y|n|o)$/i;
/** Upper-case tokens of four or more letters that are acronyms or brands, not shouting. Two- and three-letter tokens always stay as written. */
/** Short English words a shouted menu writes in capitals ("WING IT!", "11 PEOPLE PER BOAT", "TIKI BUS"). Anything else of two or three capitals is an acronym. */
const COMMON_SHORT = new Set("try st mt ft dr mr mrs jr sr ave blvd rd hwy hr hrs min mins it per for you our all new fun day sea sun bar big hot top old one two six ten and the of at in on to by or up go do we us me my an as is are was get has had can may not no off out own see set way who why how its his her him she he so if but yet any few lot low mid min max age bay hub ice ski spa gym art car cat dog fly jet rod run fit fee kid pet bus van ram raw red dry wet air fog ice hay bag box tub hat pit map mix pro pop pub inn bay cay key zip kit tip cup tap tee par pin ace ale ipa rum gin egg pie ham jam tea hop dip dye axe gun bow bat net web log".split(" "));
const CAPS_TOKENS = new Set(["YMCA", "EMTB", "BIPOC", "BWCA", "YWCA", "PADI", "NAUI", "USPA", "NASCAR", "IMAX", "NASA", "UNESCO", "HVAC", "LPGA", "USGA", "IFLY", "GOLFTEC", "SEAL", "UTVS", "ATVS", "SUPS", "PWCS", "JCC", "MMA", "BJJ", "FPV", "IFR", "VFR", "SCCA", "NHRA", "AMA", "USBC", "NCAA", "USTA", "NAUI", "SDI", "TDI", "AAU", "USAG", "FIFA", "NHL", "MLB", "NFL", "NBA", "PBR", "DIY", "ROTC", "NRA", "USCG", "TSA", "FAA", "BLM", "NPS", "NYPD", "LGBTQ", "AOPA"]);

/** "O'BRIEN" to "O'Brien", "PUTT-PUTT" to "Putt-Putt", "BILL'S" to "Bill's". */
function capWord(w: string): string {
  return w
    .split(/([-'’./])/)
    .map((part, i, all) => {
      if (i % 2) return part;
      if (!part) return part;
      const afterApos = i > 0 && /['’]/.test(all[i - 1]);
      if (afterApos && part.length <= 2) return part.toLowerCase(); // Bill's, catch'em, we'll
      return part.replace(/^([^\p{L}]*)(\p{L})(.*)$/u, (_m, pre: string, ch: string, rest: string) => pre + ch.toUpperCase() + rest.toLowerCase());
    })
    .join("");
}

/** "USPA-A", "SUP-YOGA", "PUTT-PUTT", "ST. PETE": each hyphen or slash part keeps its capitals only when it is an acronym. */
function capShouted(w: string, loneCaps: boolean): string {
  const keepLone = loneCaps && w.replace(/[^\p{L}]/gu, "").length <= 5;
  return w
    .split(/([-/])/)
    .map((part, i) => {
      if (i % 2 || !part) return part;
      const letters = part.replace(/[^\p{L}]/gu, "");
      if (!letters) return part;
      if (COMMON_SHORT.has(letters.toLowerCase())) return capWord(part);
      if (letters.length <= 3 || CAPS_TOKENS.has(letters) || !/[AEIOUY]/.test(letters) || keepLone) return part;
      return capWord(part);
    })
    .join("");
}

/** A word of four or more capitals, or an all-capitals string: the site is shouting. */
const SHOUT = /(?:^|[^A-Za-z])[A-Z][A-Z'’]{3,}(?=$|[^A-Za-z])/;
function isShouting(t: string): boolean {
  return SHOUT.test(t) || (t === t.toUpperCase() && (t.match(/[A-Z]/g) || []).length >= 4);
}

/**
 * Title-case a shouted name and nothing else. "CLEARWATER Jet ski RENTAL" reads "Clearwater Jet Ski Rental";
 * "iFLY Indoor Skydiving", "K1 Speed" and "SUP Tampa" are left exactly as written because nothing in them shouts.
 * Inside a shouted name, tokens of two or three capitals (BAE, ATX, LLC, ATV), tokens with digits (K1, 4x4)
 * and known acronyms keep their capitals; mixed-case tokens (McDonald) are never touched.
 */
export function fixShouting(raw: string): string {
  const t = raw.replace(/\s+/g, " ").trim();
  if (!t || !isShouting(t)) return t;
  const words = t.split(" ");
  const shoutedCount = words.filter((w) => /\p{Lu}/u.test(w) && w === w.toUpperCase() && /\p{L}{2}/u.test(w)).length;
  // "ROTAK Helicopter Services", "Complete BWCA Outfitting Package": one short capitalised token among cased words is a brand or an acronym.
  const loneCaps = shoutedCount === 1 && words.length >= 2;
  if (loneCaps && !words.some((w) => /\p{Lu}/u.test(w) && w === w.toUpperCase() && w.replace(/[^\p{L}]/gu, "").length > 5)) return t;
  const out = words.map((w, i) => {
    const core = w.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu, "");
    if (/^\d+(?:ST|ND|RD|TH)$/.test(core)) return w.toLowerCase(); // "JULY 4TH"
    if (!core || /\d/.test(core)) return w;
    const first = i === 0;
    const last = i === words.length - 1;
    if (SMALL_WORDS.test(core)) {
      const lower = w.toLowerCase();
      return first || last ? capWord(lower) : lower;
    }
    // "SUNSET IN LA" is Los Angeles; "LA JOLLA KAYAK" is not.
    if (core === "LA") return last || /^(?:in|of|to|from|near)$/i.test(words[i - 1] || "") ? w : capWord(w);
    if (core === core.toUpperCase()) return capShouted(w, loneCaps);
    if (core === core.toLowerCase()) return capWord(w);
    return w; // McDonald, iFLY, LaBarre: already cased on purpose
  });
  return out.join(" ");
}

/** Names that really do say a word twice. */
const REDUPLICATED = /^(?:chi|bora|walla|pago|baden|sing|duran|yo|tik|bang|cha|kai|tuk|mahi|hula|coco|boo|bling|aye|yum|hush|wiki|choo|pom|go|mau|ta|bye|la|dum|chow|lala|ping|bon|tam|kum|wagga|kaka|foo|mo|no|so|do|ha|ho|tok|cou|puka|lomi|poke|nam|bam|ra|ba|da)$/;
/** "Jet ski Jet Ski Rental" and "Bounce Bounce Trampoline Park": a word or a pair repeated back to back. "Chi Chi Rodriguez" and "Walla Walla" stay. */
export function collapseRepeats(t: string): string {
  const words = t.split(" ");
  const out: string[] = [];
  const norm = (w: string) => w.toLowerCase().replace(/[^a-z0-9]/g, "");
  const caps = (w: string) => (w.match(/\p{Lu}/gu) || []).length;
  for (const w of words) {
    const n = out.length;
    // Of two spellings ("Jet ski Jet Ski"), the better-cased one survives.
    if (n >= 1 && norm(out[n - 1]) === norm(w) && norm(w).length >= 4 && !REDUPLICATED.test(norm(w))) {
      if (caps(w) > caps(out[n - 1])) out[n - 1] = w;
      continue;
    }
    if (n >= 3 && norm(out[n - 3]) === norm(out[n - 1]) && norm(out[n - 2]) === norm(w)) {
      if (caps(out[n - 1]) > caps(out[n - 3])) out[n - 3] = out[n - 1];
      if (caps(w) > caps(out[n - 2])) out[n - 2] = w;
      out.pop();
      continue;
    }
    out.push(w);
  }
  return out.join(" ");
}

function normPlace(s: string): string {
  return s.toLowerCase().replace(/\bft\.?\s/g, "fort ").replace(/\bsaint\s/g, "st. ").replace(/\bst\s/g, "st. ").replace(/\bmt\.?\s/g, "mount ").replace(/[.,]+$/g, "").replace(/\s+/g, " ").trim();
}

/**
 * True when a tail is a place and not part of a brand. The row's own city (alone or with a geo word, "Clearwater
 * Beach", "Downtown Tampa"), a state or province by code or name, or "<place>, FL". With `anyCity`, any city in the
 * discovery grid counts too, which is right for "- St. Louis" taglines but wrong for "The Spa at Bally's"-style names.
 */
function isPlaceTail(tail: string, ctx: TitleContext, anyCity: boolean): boolean {
  const parts = tail.split(/\s*,\s*/).map(normPlace).filter(Boolean);
  if (!parts.length || parts.length > 2) return false;
  const region = ctx.region ? ctx.region.toUpperCase() : "";
  const isState = (x: string) => (x.length === 2 && x.toUpperCase() === region) || STATE_BY_NAME.has(x) || (region && STATE_NAMES[region]?.toLowerCase() === x);
  if (parts.length === 2 && !isState(parts[1])) return false;
  const head = parts[0];
  if (isState(head)) return parts.length === 1;
  const city = ctx.city ? normPlace(ctx.city) : "";
  const words = head.split(" ");
  const cityWords = new Set(city.split(" ").filter(Boolean));
  const gridCity = anyCity && CITY_NAMES.has(head);
  const rest = words.filter((w) => !cityWords.has(w) && !GEO_WORDS.test(w));
  const hasCity = city ? words.some((w) => cityWords.has(w) && w.length > 2) : false;
  if (hasCity && rest.length === 0) return true;
  if (gridCity) return true;
  // "Clearwater Beach, FL" with no city on the row: a state after the comma settles it when every word is a geo word.
  if (parts.length === 2 && rest.length <= 1) return true;
  return false;
}

/** Activity words. A remainder made only of these ("Jet Ski Adventures", "Boat Rentals") needs its place to be a name at all. */
const ACTIVITY_WORD = /^(?:jet|ski|skis|boat|boats|pontoon|kayak|kayaks|canoe|paddle|board|boards|sup|bike|bikes|e-bike|ebike|scooter|scooters|fishing|fish|parasail|parasailing|dolphin|dolphins|sunset|airboat|atv|utv|helicopter|zipline|zip|line|axe|throwing|escape|room|rooms|golf|cart|carts|surf|surfing|dive|diving|scuba|snorkel|snorkeling|sailing|sail|yacht|yachts|charter|charters|rental|rentals|tour|tours|adventure|adventures|excursion|excursions|experience|experiences|lesson|lessons|class|classes|cruise|cruises|trip|trips|ride|rides|flight|flights|session|sessions|the|and|&|of|water|sports|watersports|watersport|fun|beach|island|bay|family|private|luxury|premier|best|deep|sea|inshore|offshore|eco|manatee|shelling|sightseeing|balloon|skydiving|skydive|jetski|jetskis|wave|runner|runners|waverunner|waverunners|pedal|tiki|party|day|half|full|hour|hourly|guided|self|spa|massage|yoga|pottery|cooking|painting|wine|beer|brewery|winery|distillery|tasting|tastings|bowling|arcade|trampoline|laser|tag|karting|karts|paintball|archery|shooting|range|climbing|rock|horseback|riding|trail|trails|hiking|camping|glamping|rafting|tubing|boating|swim|swimming|snowmobile|snowmobiles|ski|snowboard|sled|dog|wildlife|nature|bird|birding|photography|ghost|food|walking|segway|trolley|bus|hop|carriage|horse|cable|gondola|train|scenic|aerial|air|glider|hang|paraglide|paragliding|skydive|tandem|indoor|outdoor|mini|putt|disc|driving|tennis|pickleball|ice|skating|rink|roller|pool|waterpark|park|zoo|aquarium|museum)$/i;
const isGenericName = (x: string) => x.split(/\s+/).every((w) => ACTIVITY_WORD.test(w.replace(/[^A-Za-z&-]/g, "")));

/** Drop " at Clearwater Beach", " in Tampa, FL", " - Tampa Bay", ", Florida" from the end when the rest is still a name. */
function stripPlaceTail(t: string, ctx: TitleContext): string {
  const twoWords = (x: string) => x.trim().split(/\s+/).length >= 2 && !isGenericName(x);
  for (let i = 0; i < 2; i++) {
    let m = t.match(/^(.*\S)\s+(?:at|in|near)\s+(?:the\s+)?([A-Za-z.'’&\s]{2,40}(?:,\s*[A-Za-z. ]{2,25})?)\s*$/i);
    if (m && twoWords(m[1]) && isPlaceTail(m[2], ctx, false)) {
      t = m[1];
      continue;
    }
    m = t.match(/^(.*\S)\s*(?:\s-\s|-\s+|\s[–—]\s?|,\s*|\|\s*)([A-Za-z.'’&\s]{2,40}(?:,\s*[A-Za-z. ]{2,25})?)\s*$/);
    if (m && twoWords(m[1]) && isPlaceTail(m[2], ctx, true)) {
      t = m[1];
      continue;
    }
    break;
  }
  return t.replace(/[\s,\-–—|:]+$/, "");
}

/** A crawled page title, not a business name: "Foo | Tampa", "JET SKI RENTAL AT CLEARWATER BEACH", all caps, or a city named twice in a long string. */
function looksSeo(raw: string, ctx: TitleContext): boolean {
  if (/\s\|\s/.test(raw)) return true;
  if (/\bAT [A-Z]{3,}/.test(raw)) return true;
  if (raw === raw.toUpperCase() && (raw.match(/[A-Z]/g) || []).length >= 4) return true;
  const words = raw.split(/\s+/);
  if (words.length >= 6 && ctx.city) {
    const c = ctx.city.toLowerCase();
    const hits = words.filter((w) => w.toLowerCase().replace(/[^a-z]/g, "") === c.replace(/[^a-z]/g, "")).length;
    if (hits >= 2) return true;
  }
  return false;
}

/**
 * The name a guest sees. Sites publish "Sky Combat Ace | San Diego", "Welcome to the Official Axe & Ale Website",
 * "FISH AND SONS KENAI CHARTERS", "CLEARWATER Jet ski RENTAL AT CLEARWATER BEACH" and "[Alchemy]". Keep the business,
 * drop the tagline, the site words, the location tail and the shouting. With a context, the operator's legal name
 * wins over a title that is plainly an SEO string.
 */
export function cleanTitle(raw: string, ctx: TitleContext = {}): string {
  const legal = (ctx.legalName || "").replace(/\s+/g, " ").trim();
  if (legal.split(" ").length >= 2 && looksSeo(raw, ctx)) return cleanTitle(legal);
  let t = raw.replace(/\s+/g, " ").trim();
  t = t.replace(/^\[(.+)\]$/, "$1").replace(/\s*\[(.*?)\]\s*$/, (_m, x: string) => (x.length <= 12 ? " " + x : "")).trim();
  t = t.replace(/^(?:welcome to|welcome)\s+(?:the\s+)?(?:official\s+)?/i, "").replace(/\s*[-–—|:]?\s*(?:official )?(?:web ?site|home ?page)\s*$/i, "").trim();
  // "A | B" and "A – B" are name plus tagline: keep the part that is a name (the first, unless it is a site word).
  // "A - B" with a plain hyphen is often one name ("Fifty - Fifty Water Sports"), so it stays whole when short.
  const isName = (x: string) => !SITE_WORDS.test(x) && !/^(?:book|reserve|call|save|best|top|#1|\d+%|free|official|voted|your|premier|the best|the #1|the premier)\b/i.test(x);
  if (/\s*(?:\||–|—)\s*/.test(t)) {
    const parts = t.split(/\s*(?:\||–|—)\s*/).map((x) => x.trim()).filter(Boolean);
    t = parts.find(isName) || parts[0];
  }
  if (/ - /.test(t)) {
    const parts = t.split(/ - /).map((x) => x.trim()).filter(Boolean);
    const named = parts.filter(isName);
    t = named.length < parts.length ? named[0] || parts[0] : t.length <= 40 ? t : parts[0];
  }
  // "Foo Charters: Best Jet Ski Rental in Tampa": an SEO clause after a colon.
  t = t.replace(/^(.{3,}?\S)\s*:\s*(?:the\s+)?(?:best|top|#\s?1|premier|your|official|voted|book|reserve)\b.*$/i, "$1");
  t = stripPlaceTail(t, ctx);
  t = collapseRepeats(fixShouting(t));
  // "labarre", "bfunk": a name typed in lower case reads as a slug. Capitalise each word; brands with inner caps are left alone.
  if (t === t.toLowerCase() && /^[a-z]/.test(t)) t = t.replace(/(^|\s)([a-z])/g, (_m, sp: string, ch: string) => sp + ch.toUpperCase());
  t = t.replace(/^[\s\-–—|:]+|[\s\-–—|:,]+$/g, "").trim();
  // "Midwest Powered Paragliding In", "Paint, Sip Wine, have fun at our": a page title cut mid-sentence.
  t = t.replace(/(?:\s+(?:of|for|with|and|or|to|our|your|at our|by|at|in)\b)+\s*$/i, "").trim();
  t = (t.length > 70 ? trimWords(t, 70) : t).replace(/[\s\-–—|:,]+$/g, "");
  // Never a stub or a bare domain: fall back to the legal name, then to the raw title.
  if (t.length < 3 || /^(?:https?:\/\/|www\.)|^[a-z0-9-]+\.[a-z]{2,}$/i.test(t)) return legal.length >= 3 ? legal : raw.trim();
  return t;
}

/** Cut at a word boundary, no ellipsis, so a name never ends mid-word. */
function trimWords(t: string, max: number): string {
  if (t.length <= max) return t;
  return t.slice(0, max).replace(/\s+\S*$/, "").trim();
}

/** Cut at the last sentence end inside the limit, so a blurb never stops mid-thought. */
function endAtSentence(t: string, max: number): string {
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  const i = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("! "), cut.lastIndexOf("? "));
  return (i > max * 0.4 ? cut.slice(0, i + 1) : trimWords(cut, max)).trim();
}

/** A line the crawl took from a heading, a nav bar or a banner: no sentence end, short, and mostly capitals. */
function isHeadingLine(l: string): boolean {
  if (/[.!?]["”’)]?$/.test(l)) return false;
  const words = l.split(" ");
  if (words.length > 10) return false;
  if (/:$/.test(l) && words.length <= 6) return true;
  const letters = l.replace(/[^A-Za-z]/g, "");
  if (letters.length >= 3 && letters === letters.toUpperCase()) return true;
  const caps = words.filter((w) => /^[A-Z0-9$#&]/.test(w) || SMALL_WORDS.test(w)).length;
  return caps / words.length >= 0.7;
}

const STATE_CODE = /^(?:AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC|AB|BC|MB|NB|NL|NS|NT|NU|ON|PE|QC|SK|YT)$/;
const PHONE = /\(?\b\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}\b/g;
const NAV_WORD = /\b(?:home|about(?: us)?|contact(?: us)?|book now|gift cards?|faqs?|menu|login|sign in|cart)\b/gi;

/**
 * Cut the keyword-stuffed run that opens "Clearwater Jet Ski Dolphin Tours CLEARWATER JET SKI RENTAL AT CLEARWATER
 * BEACH, FL The premier jet ski rental company in Clearwater, Florida." A run of capitalised words is only cut at a
 * clear seam (two or more shouted words, or a state after a comma) and only when a real sentence follows; "Indian
 * Rocks Beach Boat Rental offers a variety of boats" has no seam and is kept whole.
 */
function cutLeadingFragment(t: string): string {
  const first = t.match(/^[^.!?]*(?:[.!?]|$)/)?.[0] ?? t;
  const words = first.split(" ");
  let runEnd = 0;
  while (runEnd < words.length) {
    const w = words[runEnd];
    const core = w.replace(/^[^A-Za-z0-9]+|[^A-Za-z0-9]+$/g, "");
    if (!core || /^[A-Z0-9$#&]/.test(core) || SMALL_WORDS.test(core)) runEnd++;
    else break;
  }
  if (runEnd < 3) return t;
  let cut = 0;
  let capsRun = 0;
  for (let i = 0; i < runEnd; i++) {
    const w = words[i];
    const core = w.replace(/^[^A-Za-z0-9]+|[^A-Za-z0-9]+$/g, "");
    const shouted = core.length >= 2 && /[A-Z]/.test(core) && core === core.toUpperCase() && !/\d/.test(core);
    if (shouted && SMALL_WORDS.test(core)) {
      // "THE BEER THE SNACKS EVENTS AND MORE": a shouted "and" is part of the banner, not a break in it.
      if (capsRun) capsRun++;
      if (capsRun >= 2) cut = i + 1;
    } else if (shouted && !STATE_CODE.test(core)) {
      capsRun++;
      if (capsRun >= 2) cut = i + 1;
    } else if (shouted && STATE_CODE.test(core) && i > 0 && /,$/.test(words[i - 1])) {
      cut = i + 1;
      capsRun = 0;
    } else if (i > 0 && /,$/.test(words[i - 1]) && STATE_BY_NAME.has(core.toLowerCase())) {
      cut = i + 1;
      capsRun = 0;
    } else capsRun = 0;
  }
  if (!cut || cut >= words.length) return t;
  const rest = words.slice(cut).join(" ").replace(/^[\s,.:;|–-]+/, "");
  const restAll = rest + t.slice(first.length);
  if (!/^[A-Z"“]/.test(restAll) || rest.length < 30 || !/\s[a-z]{2,}\s/.test(rest)) return t;
  return restAll;
}

/**
 * The paragraph a guest reads under the title. It must open on a real sentence: heading lines, a leading repeat of
 * the name or the city, keyword runs, "Welcome to X!" (when more follows) and phone numbers go; the first letter is
 * upper case, sentences sit one space apart, and the text ends on a sentence inside 600 characters. Navigation text
 * and anything under 40 characters come back empty, since an empty blurb beats junk.
 */
export function cleanBlurb(raw: string, ctx: { title?: string; city?: string | null; region?: string | null } = {}): string {
  if (!raw) return "";
  const lines = raw.split(/\r?\n+/).map((l) => l.replace(/\s+/g, " ").trim()).filter(Boolean);
  const body = lines.length > 1 ? lines.filter((l) => !isHeadingLine(l)) : lines;
  // cleanPara strips markdown "#"; "#1 dolphin tour" is copy, so the hash before a digit is parked and restored.
  let t = cleanPara(body.join(" ").replace(/#(?=\d)/g, "\u0001")).replace(/\u0001/g, "#").replace(PHONE, " ").replace(/\s+/g, " ").trim();
  // A case-insensitive literal without the i flag, so the "next word is capitalised" lookahead stays case-sensitive.
  const esc = (s: string) =>
    s
      .trim()
      .split(/\s+/)
      .map((word) => [...word].map((ch) => (/\p{L}/u.test(ch) && ch.toLowerCase() !== ch.toUpperCase() ? "[" + ch.toLowerCase() + ch.toUpperCase() + "]" : ch.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))).join(""))
      .join("\\s+");
  const region = ctx.region ? ctx.region.toUpperCase() : "";
  const stateAlt = (region ? "(?:" + esc(STATE_NAMES[region] || region) + "|" + region + ")" : "[A-Z]{2}") + "\\b";
  for (let i = 0; i < 4; i++) {
    const before = t;
    // "Welcome to Makin' Waves! We are ..." keeps the second sentence.
    t = t.replace(/^welcome (?:to|aboard)\b[^.!?]{0,80}[.!?]["”]?\s+(?=\S)/i, "");
    // A leading repeat of the name as a label ("Siesta Dolphin Tours - Siesta Key's #1 ...", "Makin Waves: We are ..."), never the name as a subject ("Allure Boat Rentals offers ...").
    if (ctx.title) t = t.replace(new RegExp("^" + esc(ctx.title) + "(?:\\s*[-–—|:]+\\s*|[.!]\\s+)(?=[A-Z\"“(])"), "");
    // "Tampa, FL The premier ..." and "Clearwater Beach FL - We rent ...": a city with its state or a separator, never "Whistler Paintball offers ...".
    if (ctx.city) t = t.replace(new RegExp("^" + esc(ctx.city) + "(?:\\s+(?:[Bb]each|[Bb]ay|[Ii]sland|[Aa]rea))?(?:,?\\s+" + stateAlt + "\\s*[,.:|–—-]*\\s*|\\s*[,.:|–—-]+\\s*(?!" + stateAlt + "))(?=[A-Z\"“(])"), "");
    t = cutLeadingFragment(t);
    // "... in Clearwater, Florida. RENT BY THE HOUR As Low as $85" keeps a shouted banner between sentences.
    t = t.replace(/(^|[.!?]["”]?\s+)(?:[A-Z][A-Z'’&-]+\s+){3,}(?=[A-Z][a-z])/g, "$1");
    t = t.replace(/^[\s,.:;|–—-]+/, "");
    if (t === before) break;
  }
  // "iFLY", "i Tour Puerto Rico" and "barre3" are brands; any other opener gets its capital.
  if (!/^(?:\p{Ll}\p{Lu}|\p{Ll}\s+\p{Lu}|\p{Ll}+\d)/u.test(t)) t = t.charAt(0).toUpperCase() + t.slice(1);
  t = endAtSentence(t, 600);
  if (t.length < 40) return "";
  if ((t.match(NAV_WORD) || []).length >= 3) return "";
  // A blurb that is mostly capitals is a banner or a policy line, not copy.
  const letters = t.replace(/[^A-Za-z]/g, "");
  if (letters.length && (t.replace(/[^A-Z]/g, "").length / letters.length) >= 0.5) return "";
  // No sentence end: a meta description the crawler cut short ("... beauty of Earth's amazing"), a keyword list
  // ("surf surfboard stand up paddle SUP kayak") or a comma-chain of tags. Real prose is closed at its last clause
  // when that keeps most of it; the rest is dropped, since an empty blurb beats a line that stops mid-thought.
  if (!/[.!?]["”’)]?$/.test(t)) {
    // "... in the state of", "... selecting the perfect": a line that stops on a function word was cut mid-phrase.
    const DANGLING = /(?:\s+(?:and|or|the|a|an|of|with|for|to|in|at|by|from|&|your|our|their|its|his|her|my|as|that|which|is|are|was|be|been|has|have|will|can|near|over|into|on|s|perfect|best|great|new|ultimate|unique|most|very|more|all|every|each|this|these|those|some|any|such|own|next|first|last|only|no))+[\s,;:–—-]*$/i;
    const commas = (t.match(/,/g) || []).length;
    // "... redfish, trout, grouper, snapper, snook and": a list missing only its last item closes as it stands.
    const openList = commas >= 2 && /,\s+\S+\s+(?:and|or|&)$/i.test(t);
    // "... to meet all your boating": a determiner one word from the end was mid-phrase too.
    const cutShort = !openList && (DANGLING.test(t) || /\s(?:the|your|our|all|its|their|his|her|my|a|an)\s+\S+$/i.test(t) || t.length >= 140);
    t = t.replace(DANGLING, "");
    const words = t.split(" ").length;
    // Prose carries function words; "surf surfboard stand up paddle SUP kayak windsurf" and "Basic / Rental / Group Packages" carry none.
    const functionWords = (t.match(/\b(?:the|a|an|and|of|to|in|is|are|we|our|you|your|with|for|on|at|by|from|it|its|this|that|or|as|be)\b/gi) || []).length;
    if (words < 8 || functionWords < words / 8 || commas >= 6) return "";
    if ((t.match(/\b[A-Z][a-z]+:\s/g) || []).length >= 3) return ""; // "Elevation: 1,516 feet Area Code: 530 Zip Code:"
    if (cutShort) {
      // Crawlers cut meta descriptions near 160 characters. The text can only be closed before a trailing modifier
      // clause (", offering ...", ", which ...", " – ...") that leaves most of the words and no half-finished list.
      let best = -1;
      for (const m of t.matchAll(/,\s(?=(?:[a-z]+ing\s+[a-z]|(?:and|which|where|while|but|so|plus|including)\b))|\s(?:while|whether)\s|\s[–—]\s/g)) {
        const head = t.slice(0, m.index);
        const keep = head.split(" ").length;
        if (keep >= 8 && keep >= words * 0.55 && !/,\s+\S+(?:\s+\S+){0,2}$/.test(head)) best = m.index!;
      }
      if (best < 0) return "";
      t = t.slice(0, best).replace(/[\s,;:–—-]+$/, "") + ".";
    } else t = t.replace(/[\s,;:–—-]+$/, "") + ".";
  }
  return t;
}

/** "Ultimate Tour (ULT) Rates For 3 or more passengers ..." starts with the title and widget labels. Keep the copy. */
function scrubDesc(name: string, desc: string): string {
  let d = desc.replace(/\s+/g, " ").trim();
  const n = name.replace(/\s+/g, " ").trim();
  if (n && d.toLowerCase().startsWith(n.toLowerCase())) d = d.slice(n.length).replace(/^[\s:\-–|]+/, "");
  d = d.replace(/^(?:(?:rates?|pricing|prices?|duration|about(?: this)?|flight distance|(?:\w+ )?details?|overview|description|read more|learn more)\s*:?\s*)+/i, "");
  d = d.replace(/\b(?:Duration|Meeting Location|Rates?|About This|Flight Distance)\s*:?\s*(?=[A-Z0-9$])/g, "");
  return d.trim();
}

const SPIRITS = /\b(brandy|whiskey|whisky|bourbon|rye|gin|vodka|rum|tequila|mezcal|liqueur|mead|cider|ipa|lager|stout|ale|pinot|cabernet|chardonnay|merlot|rosé|rose wine|reserve|barrel|cask|vintage)\b/i;
const MERCH = /\b(t-?shirts?|hoodies?|sweatshirts?|hats?|caps?|stickers?|mugs?|koozies?|\d{3}\s?ml|bottles?|6-?pack|case of|gift ?cards?|gift certificates?|crossbows?|bows?\b|arrows?|broadheads?|quiver|scopes?|ammo\b|ammunition|merch(andise)?|apparel|decals?|posters?|dvd|membership dues|donation|sponsor(ship)?|field trip|school group)\b/i;

function hostOf(url: string): string {
  try {
    return new URL(url.startsWith("http") ? url : "https://" + url).hostname.toLowerCase().replace(/^www\./, "");
  } catch {
    return url.toLowerCase();
  }
}

/** graylinetoronto.tours and graylinetoronto.com are one brand; so is mammothpack.wixsite.com for mammothpack.com. */
function sameBrand(url: string | null, domain: string): boolean {
  if (!url) return false;
  const host = hostOf(url);
  const label = (d: string) => d.replace(/^www\./, "").split(".")[0];
  const own = label(domain);
  if (own.length < 5) return false;
  if (/\.(wixsite|squarespace|weebly|godaddysites|wordpress|webflow\.io|myshopify|square\.site|business\.site)\b/.test(host)) return host.startsWith(own) || host.includes(own);
  return label(host) === own;
}

/** True when the page belongs to the operator (or a booking widget acting for them). Another business's site never counts. */
function sourceIsOwn(url: string | null, domain: string): boolean {
  if (!url) return true;
  let host = "";
  try {
    host = new URL(url).hostname.toLowerCase().replace(/^www\./, "");
  } catch {
    return true;
  }
  const own = domain.toLowerCase().replace(/^www\./, "");
  if (host === own || host.endsWith("." + own)) return true;
  return WIDGET_HOSTS.test(host);
}

const CITY_SLUGS: Map<string, string> = (() => {
  const m = new Map<string, string>();
  for (const c of CITIES) m.set(slug(c.name), c.name.toLowerCase());
  return m;
})();

/** A page under /locations/greensboro or /birthdays/anderson belongs to a branch in another town, not to this listing. */
function sourceIsAnotherTown(url: string | null, city: string | null, metroId: string | null): boolean {
  if (!url || !city) return false;
  let path = "";
  try {
    path = new URL(url).pathname.toLowerCase();
  } catch {
    return false;
  }
  const own = new Set([slug(city), metroId ? slug(metroId) : ""]);
  for (const seg of path.split("/")) {
    if (seg.length < 5) continue;
    const hit = CITY_SLUGS.get(seg) || (seg.replace(/-(location|branch|park|store)$/, "") !== seg ? CITY_SLUGS.get(seg.replace(/-(location|branch|park|store)$/, "")) : undefined);
    if (hit && !own.has(seg) && !own.has(slug(hit)) && !slug(city).includes(seg) && !seg.includes(slug(city))) return true;
  }
  return false;
}

/** "$35 per lane" is a lane, not a boat; "$1,200 each" on a charter is the whole trip, not a seat. */
function fixUnit(o: { name: string; detail: string | null; price_cents: number | null; price_unit: string | null }): string | null {
  const text = (o.name + " " + (o.detail || "")).toLowerCase();
  if (/per (lane|room|cart|bay|court|table|booth|cabana|pod|suite)\b/.test(text)) return "/group";
  if (/per (boat|charter|vessel|yacht)\b/.test(text)) return "/boat";
  if (/per (person|adult|child|guest|rider|passenger|player|jumper|diver|student)\b|\bpp\b/.test(text)) return "each";
  if ((o.price_unit == null || o.price_unit === "each") && (o.price_cents || 0) >= 60000) return "/group";
  return o.price_unit;
}

/** One clean statement: not a question, not a mashed paragraph, not a scraped aside. */
/** "Must be 21 with ID" and "All participants must be age 21 or older with a valid ID" say one thing. Keep the shortest per topic. */
function collapseRules(lines: string[]): string[] {
  const byKey = new Map<string, string>();
  const order: string[] = [];
  for (const l of lines) {
    const nums = (l.match(/\d+/g) || []).join(",");
    const tail = l.match(/:\s*(minimum \d+ (guests?|people|riders?|passengers?) per booking\.?)$/i);
    if (tail) {
      const key = "min:" + tail[1].toLowerCase();
      if (!byKey.has(key)) {
        byKey.set(key, tail[1].charAt(0).toUpperCase() + tail[1].slice(1));
        order.push(key);
      }
      continue;
    }
    const topic = /\b(age|years?|old|older|minor|child|kid|adult|\d+\s*\+)\b/i.test(l) ? "age" : /\b(weight|lbs?|pounds?|kg)\b/i.test(l) ? "weight" : /\b(height|tall|inches|cm)\b/i.test(l) ? "height" : /\b(licen[cs]e|permit|boater)\b/i.test(l) ? "license" : "";
    const key = topic && nums ? topic + ":" + nums : l.toLowerCase();
    const cur = byKey.get(key);
    if (!cur) {
      byKey.set(key, l);
      order.push(key);
    } else if (l.length < cur.length) byKey.set(key, l);
  }
  return order.map((k) => byKey.get(k)!);
}

/** Wix lazy-load placeholders are 34px blurred stubs. Ask for the full image instead; tiny variants from other hosts are dropped. */
function fullSize(u: string): string | undefined {
  if (!u) return undefined;
  const wix = u.match(/^(https?:\/\/static\.wixstatic\.com\/media\/[^/]+?)(?:\/v1\/|$)/);
  if (wix) return wix[1] + "/v1/fill/w_1600,h_1000,al_c,q_85/" + wix[1].split("/media/")[1].replace(/%7E/gi, "~");
  if (/[?&/](w|width)[=_]\d{1,2}\b|[?&/](h|height)[=_]\d{1,2}\b|blur_\d|\/w_1?\d{2},h_\d{2}\b/.test(u)) return undefined;
  return u;
}

const SILENT = /\b(not|no|none|nothing)\b[^.]{0,50}\b(stated|specified|listed|mentioned|provided|published|given|indicated)\b|\bnot (state|specify|mention|list)\b|\bunspecified\b|\bn\/a\b|\bno information\b/i;
/** A value that only says "not stated" is no value. */
function silent(v: string | null | undefined): string | null {
  return v && !SILENT.test(v) ? v : null;
}
/** Remove sentences that only say a policy is absent. */
function dropSilent(t: string): string {
  return t.split(/(?<=[.!?])\s+/).filter((x) => !SILENT.test(x)).join(" ").trim();
}

function isTidyLine(l: string): boolean {
  if (l.length < 6 || l.length > 150) return false;
  // "Deposit policy not stated" tells a guest nothing; the extractor writes these when a site is silent.
  if (SILENT.test(l)) return false;
  if (/\?\s*$/.test(l) || /\?\s+[A-Z]/.test(l)) return false;
  if (/^(and|but|or|so|also|please note|note:|p\.s\.)\b/i.test(l)) return false;
  if (/\b(duration|meeting location|rates?)\b.*\$\d/i.test(l)) return false;
  if (/not limited to|click|subscribe|newsletter|follow us/i.test(l)) return false;
  return true;
}

/** Things a site sells that a guest does not book a time for. */
const NOT_A_SERVICE = /\b(gift ?cards?|gift certificates?|e-?gift|merch(andise)?|t-?shirts?|hats?|apparel|donation|membership|season pass|parking)\b/i;

function uniq(list: string[]): string[] {
  const seen = new Set<string>();
  return list.filter((x) => x && !seen.has(x.toLowerCase()) && (seen.add(x.toLowerCase()), true));
}

const NAMED: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " ", rsquo: "\u2019", lsquo: "\u2018", ldquo: "\u201c", rdquo: "\u201d", ndash: "\u2013", mdash: "\u2014", hellip: "\u2026", copy: "\u00a9", reg: "\u00ae", trade: "\u2122", deg: "\u00b0", eacute: "\u00e9" };
/** Sites leave HTML entities in meta descriptions and menus. Guests should never see "&amp;". Runs twice for double-encoded text. */
export function decodeEntities(raw: string): string {
  const once = (t: string) =>
    t.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, code: string) => {
      if (code[0] === "#") {
        const n = code[1].toLowerCase() === "x" ? parseInt(code.slice(2), 16) : parseInt(code.slice(1), 10);
        return Number.isFinite(n) && n > 0 ? String.fromCodePoint(n) : m;
      }
      return NAMED[code.toLowerCase()] ?? m;
    });
  return once(once(raw));
}

/** Markdown, image tags and widget leftovers out; one clean sentence in. */
function cleanLine(raw: string): string {
  return raw
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[#*_>`]+/g, " ")
    .replace(/https?:\/\/\S+/g, "")
    .replace(/^\s*(?:\(?\d{1,2}[.)]|[-–•·]|[a-z][.)]|[AQ]\s*[-–:])\s+/i, "")
    // "Additional Information: ...", ": Daytime only 9-5", "SUNDAY----10am-9PM": scraped labels and separators, not words.
    .replace(/^\s*(?:additional (?:information|info|details)|please note|note|important|(?:cruise|tour|trip|lesson|class|event|package) details)\s*[:\-–]\s*/i, "")
    .replace(/^[\s:;,.\-–—|]+/, "")
    .replace(/\s*-{2,}\s*/g, " – ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 240);
}

function cleanPara(raw: string): string {
  const flat = raw
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[#*_>`]+/g, " ")
    .replace(/https?:\/\/\S+/g, "")
    .replace(/\s+/g, " ")
    .trim();
  // Sites repeat the same sentence in two places. Keep each once, and never cut mid-sentence.
  const seen = new Set<string>();
  const out: string[] = [];
  let len = 0;
  for (const sentence of flat.split(/(?<=[.!?])\s+(?=[A-Z0-9"(])/)) {
    const key = sentence.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
    if (!key || seen.has(key)) continue;
    if (len + sentence.length > 700) break;
    seen.add(key);
    out.push(sentence);
    len += sentence.length + 1;
  }
  if (out.length > 1 && !/[.!?)"]$/.test(out[out.length - 1])) out.pop();
  return out.join(" ");
}

/** FAQ facts come as "Question? >Answer", "Q – Question? A – Answer", or several of those packed together. */
function parseFaqs(raw: string): { q: string; a: string }[] {
  const t = cleanPara(raw).replace(/\bA\s*[-–:]\s*/g, " ").trim();
  const chunks = t.split(/\bQ\s*[-–:.]\s*/).map((c) => c.trim()).filter(Boolean);
  const out: { q: string; a: string }[] = [];
  for (const c of chunks) {
    const i = c.indexOf("?");
    if (i < 8 || i > 160) continue;
    const before = c.slice(0, i + 1);
    const cut = Math.max(before.lastIndexOf(". "), before.lastIndexOf("! "));
    let q = before.slice(cut === -1 ? 0 : cut + 2).replace(/^[\s\-–—•·:]+/, "").trim();
    // "Ride the Boomerang Yacht Trips Can I buy a ticket at check-in?" carries a scraped heading before the question.
    if (q.split(" ").length > 9) {
      const m = q.match(/^(.*?\S)\s+((?:Can|Could|Do|Does|Did|Is|Are|Was|Were|What|How|Where|When|Why|Which|Will|Would|Should|May|Am|Who)\b.*\?)$/);
      if (m && m[1].split(" ").length >= 2) q = m[2];
    }
    // The answer ends where the next question begins.
    let a = c.slice(i + 1).replace(/^\s*>\s*/, "").trim();
    const next = a.search(/[.!]\s+[A-Z][^.!?]{8,120}\?/);
    if (next > 20) a = a.slice(0, next + 1);
    if (q.length < 8 || a.length < 12) continue;
    out.push({ q, a: a.slice(0, 500) });
  }
  return out;
}

function uniqBy<T>(list: T[], key: (t: T) => string): T[] {
  const seen = new Set<string>();
  return list.filter((x) => !seen.has(key(x)) && (seen.add(key(x)), true));
}

/** Write public/catalog.json: every real operator plus its contact facts. The app fetches it at startup. */
export function syncCatalogToApp(): { path: string; count: number } {
  const rows = db
    .prepare(
      `SELECT id, domain, name, legal_name, website, city, region, metro_id, family, icon_key, rating, review_count, origin, lat, lon
       FROM operators WHERE origin != 'demo' AND name IS NOT NULL AND length(name) >= 3
       ORDER BY completeness DESC, name ASC`,
    )
    .all() as CatalogRow[];
  const dead = new Set(
    (db.prepare(
      `SELECT o.id FROM operators o WHERE o.website IS NULL AND o.phone IS NULL
         AND NOT EXISTS (SELECT 1 FROM facts f WHERE f.operator_id = o.id AND f.fact_key = 'cover')
         AND NOT EXISTS (SELECT 1 FROM offerings x WHERE x.operator_id = o.id)`,
    ).all() as { id: string }[]).map((r) => r.id),
  );
  // A listing with no site, no phone, no photo and no menu gives a guest nothing to act on. Keep it for outreach only.
  const full = rows
    .filter((r) => !MARKETPLACES.test(r.domain) && !dead.has(r.id) && !NOT_EXPERIENCE.test(r.name) && !/^\s*\$?\d+(\.\d+)?\s*$/.test(r.name))
    // "Home", "Welcome" and a bare domain are page titles, not business names. A guest cannot tell what they are.
    .filter((r) => { const t = cleanTitle(decodeEntities(r.name), { city: r.city, region: r.region, legalName: r.legal_name }); return t.length >= 3 && !SITE_WORDS.test(t) && !NAV_LABEL.test(t) && !GENERIC_TITLE.test(t) && !/^(?:https?:\/\/|www\.)/i.test(t); })
    // Outside the US and Canada, by pin or by address, is outside the market (a Cairns balloon flight tagged HI).
    .filter((r) => (r.lat == null || r.lon == null || inNorthAmerica(r.lat, r.lon)) && (!r.region || r.region.length !== 2 || NA_REGION.test(r.region.toUpperCase())))
    .map(toCatalogItem)
    .map((item) => {
      const ov = profileOverlay(String(item.id));
      if (!ov) return item;
      const base = item as unknown as Record<string, unknown>;
      const merged: Record<string, unknown> = { ...base, ...ov.patch, id: base.id, claimKey: base.claimKey, claimed: true, published: ov.published };
      return merged as unknown as typeof item;
    })
    .filter((item) => (item as unknown as { published?: boolean }).published !== false);
  // A map pin and the operator's own site for the same business in the same metro: keep the site row, drop the pin.
  const siteKeys = new Set(full.filter((i) => !String(i.id).startsWith("o-osm-")).map((i) => titleKey(String(i.title)) + "|" + (i.metroId || i.area)));
  const pinDupes = full.filter((i) => String(i.id).startsWith("o-osm-") && siteKeys.has(titleKey(String(i.title)) + "|" + (i.metroId || i.area)));
  for (const d of pinDupes) full.splice(full.indexOf(d), 1);
  console.log("Left out " + dead.size + " map-only rows with nothing a guest can use and " + pinDupes.length + " map pins that duplicate a site row.");
  const contactByDomain: Record<string, OperatorContact> = {};
  for (const c of allContacts()) contactByDomain[c.domain] = c;

  // One small file per operator with everything: services, photos, videos, facts, contact.
  const dir = join(appDataDir, "../../public/o");
  mkdirSync(dir, { recursive: true });
  const keep = new Set<string>();
  for (const item of full) {
    const c = contactByDomain[String(item.src)];
    const contact = c
      ? { domain: c.domain, phone: c.phone, street: c.street, city: c.city, region: c.region, postal: c.postal, hours: c.hours }
      : undefined;
    const file = item.id + ".json";
    keep.add(file);
    writeFileSync(join(dir, file), JSON.stringify({ ...item, contact }));
  }
  for (const f of readdirSync(dir)) if (!keep.has(f)) unlinkSync(join(dir, f));

  // The browse catalog carries only what cards, rails and search need. Details load per listing.
  const operators = full.map((item) => {
    const options = (item.options as { price: number | null }[]) || [];
    const priced = options.map((o) => o.price).filter((n): n is number => n != null && n > 0);
    return {
      id: item.id, title: item.title, cat: item.cat, art: item.art, area: item.area, metroId: item.metroId, src: item.src,
      rating: item.rating, reviews: item.reviews, lat: item.lat, lon: item.lon, cover: item.cover, video: item.video,
      locations: item.locations,
      tags: ((item.tags as string[]) || []).slice(0, 6),
      from: priced.length ? Math.min(...priced) : undefined,
      dur: item.dur, fc: item.fc,
      // First day-specific deal, compact ("3,5|Glow nights $25"), so cards can badge "Deal today" without the detail file.
      deal: (() => {
        const p = ((item.promos as { text: string; days: number[] }[] | undefined) || []).find((x) => x.days.length);
        return p ? p.days.join(",") + "|" + p.text.slice(0, 40) : undefined;
      })(),
      // Compact week from the published hours, so the home page can say "open now" without a detail file.
      hrs: (() => {
        const own = (item.hoursText as string[] | undefined) || [];
        const c = contactByDomain[String(item.src)];
        const lines = own.length ? own : c?.hours || [];
        return lines.length ? encodeWeek(lines) || undefined : undefined;
      })(),
      options: [], specs: [], includes: [], gap: "", lite: true,
    };
  });
  const path = join(appDataDir, "../../public/catalog.json");
  writeFileSync(path, JSON.stringify({ generatedAt: new Date().toISOString(), operators, contacts: {} }));
  // The lite shard: what the home rails and the first search need, about a fifth of the size. Photo, price and reviews first.
  const lite = (operators as { cover?: unknown; from?: unknown; reviews?: unknown; metroId?: unknown }[])
    .map((o) => ({ o, s: (o.cover ? 4 : 0) + (o.from != null ? 3 : 0) + Math.min(3, Math.log10((Number(o.reviews) || 0) + 1)) + (o.metroId ? 1 : 0) }))
    .sort((a, b) => b.s - a.s)
    .slice(0, 2200)
    .map((x) => x.o);
  writeFileSync(join(appDataDir, "../../public/catalog-lite.json"), JSON.stringify({ generatedAt: new Date().toISOString(), operators: lite, contacts: {} }));
  const pages = writeLandingPages(full as never);
  console.log("Wrote " + pages.pages + " landing pages to public/p");
  return { path, count: operators.length };
}
